var JS=0,GWT=1,svgInjector=Similitude.svgInjector,SVGTools=Similitude.SVGTools,floatFmt=function(a){var b=Math.pow(10,1);return String(Math.round(a*b)/b)};window.isSupportedBrowser=function(){return bowser.msie&&9>=bowser.version?!1:!0};var classListRemove=function(a,b){return a.replace(RegExp("( "+b+"($|(?= ))|(^|(?= ))"+b+" |^"+b+"$)","g"),"")};
window.changedMinColRes=function(a){var b=[240,400],d=[4,4],c=[10,10];console.log("xymin 0 "+floatFmt(a[0])+"xymin 1 "+floatFmt(a[1]));b=(a[0]/b[0]+a[1]/b[1])/2;d=[b*d[0],b*d[1]];a=[a[0]-b*c[0],a[1]-b*c[1]];a=".tri-fold_colContent { box-shadow: "+d[0].toString()+"px "+d[1].toString()+"px 4px rgba(50, 50, 50, 0.58); width: "+a[0].toString()+"px; height: "+a[1].toString()+"px; }";document.styleSheets[1].deleteRule(0);document.styleSheets[1].insertRule(a,0)};
window.b64toBlob=function(a){a=atob(a);var b,d=a.length,c=new Uint8Array(d);for(b=0;b<d;++b)c[b]=a.charCodeAt(b);return c};
var Replacer=function(a,b){this.D0=a;this.F1=b},ZipModder=function(a,b,d,c){var e=this;e.W0=a;e.G=b;e.F0=d;e.B0=c;e.a0=!1;e.G1=0;e.R=!1;e.S=[];e.h=function(a,b){var d=this;if(d.R)d.S.push(a);else{d.R=!0;var c=new XMLHttpRequest;c.open("GET",b,!0);c.responseType="arraybuffer";c.onreadystatechange=function(){console.log(c.readyState.toString());if(4==c.readyState)for(d.G1=new JSZip(c.response),d.a0=!0,d.U0(a);0<d.S.length;){var b=d.S.splice(0,1)[0];d.U0(b)}};c.send(null)}};e.U0=function(a){if(!this.a0){if(this.G===
ZipModder.URL){this.h(a,this.W0);return}this.a0=!0;this.G1=new JSZip(this.G===ZipModder.B64?window.b64toBlob(this.K,"",512):this.K)}var b,d,c,l=this.G1;for(b=0;b<e.F0;b++)l=e.F0[b](l,a);for(b=0;b<e.B0.length;b++){c=l.file(e.B0[b].D0).asText();window.text=c;for(d=0;d<e.B0[b].F1.length;d++)c=e.B0[b].F1[d](c,a);l.remove(e.B0[b].D0);l.file(e.B0[b].D0,c)}saveAs(l.generate({type:"blob",compression:"store"}),a.filename)};return function(a){e.U0(a)}};ZipModder.URL=0;ZipModder.BLOB=1;ZipModder.B64=2;
var replaceStyleValues=function(a,b){var d=b.currentStyleSheetNum;a.replace("DemoStyle1.css","ActiveSheet.css");a.replace("DemoStyle2.css","DemoStyle"+(1+(d+1)%2).toString()+".css");a.replace("DemoStyle3.css","DemoStyle"+(1+(d+2)%2).toString()+".css");a.replace("ActiveSheet.css","DemoStyle"+d.toString()+".css");return a},replaceConfigSection=function(a,b){var d=a.search("//begin customized config"),c=a.search("//end customized config");return a.substr(0,d)+b.configCode+a.substr(c+23)};
window.downloadCallbacks={};window.downloadCallbacks[JS]=new ZipModder("resources/TriFold_Example.zip",ZipModder.URL,[],[new Replacer("TriFold_Example/TriFold-Demo.html",[replaceStyleValues,replaceConfigSection])]);window.downloadCallbacks[GWT]=new ZipModder("resources/GWTriFold_SampleApp.zip",ZipModder.URL,[],[new Replacer("GWTriFold_SampleApp/src/com/website/sample/client/Sample.java",[replaceConfigSection]),new Replacer("GWTriFold_SampleApp/src/com/website/sample/Sample.gwt.xml",[replaceStyleValues])]);
var COL_CONSTS=["LEFT","CENT","RIGHT"],MODE_CONSTS=["FIXED","SLIDE","CAN_MINIMIZE"],AVAIL_CONSTS=["ONE_AVAILABLE","TWO_AVAILABLE","THREE_AVAILABLE"],ROLLOVER_CONSTS=["NO_ROLLOVER","ROLLOVER","ROLLOVER_OPT"],CODE_SAMPLE={1:{PREFACE:"private GWTriFold createGWTriFold(Panel parent,<br/> Panel leftCol, Panel centerCol, Panel rightCol) {<br/><br/>DefaultBehavior behavior = new DefaultBehavior();<br/>",HAS_ARGS:[["","<br/>"],["","<br/>"]],MIDPOINT:"GWTriFold triFold = GWTriFold.create(behavior, <div class='longindent'>leftCol, centerCol, rightCol);</div>",
SUFFIX:"triFold.addTo(parent);<br/>return triFold;<br/>}"},0:{PREFACE:"function createTriFold(parentDiv,<div class='longindent'>leftDiv, centDiv, rightDiv) {</div><br/>var Behavior = TriFold.DefaultBehavior;<br/>var behavior = new Behavior();<br/>",HAS_ARGS:[["behavior.setOpts({<div class='indent'>","});</div>"],["triFold.setOpts({<div class='indent'>","});</div>"]],MIDPOINT:"var triFold = new TriFold(behavior, <div class='longindent'>leftDiv, centDiv, rightDiv);</div>",SUFFIX:"triFold.addTo(parentDiv);<br/>return triFold;</div><br/>}"}},
consoleLog=function(a){"debugLog"in(window.triFold._proto_||window.triFold.constructor.prototype)&&window.triFold[0].debugLog("DEMO:"+a);console.log(a)},genElement=function(a,b){var d=document.createElement("div");d.className=b;0!==a&&a.appendChild(d);return d},addSvg=function(a,b,d){svgInjector.addSvgVariantsBright(a,b,d,"")},addSvgVariantsBrightStroke=function(a,b,d){svgInjector.addSvgVariants(a,[[b,d," brightbg","",0],[b,d," darkbg","darkbg",function(a){SVGTools.replaceStyle(a,["path"],"stroke",
"#FFFFFF")}]])};
function ConfigDemoJS(a,b,d,c,e){var f=this;f.i=a;var k,h,g;for(d=0;3>d;d++)for(h=f.i.getCol(d),k=0;3>k;k++)d!=k&&(g=h.getElementsByClassName("tri-fold_buttonCol"+k.toString()),addSvg(g[0],0==k?"gear-2":1==k?"note-11":"icon_6041",0));d=document.body.getElementsByClassName("logo")[0];addSvgVariantsBrightStroke(d,"logo","",0);d.style.display="block";d.style.display="inline-block";f.S0=b.copy();f.T0=!1;f.E1=[];f.I0=[];f.A0=1;f.E0=[];b=genElement(c,"content configcolcontent");e=genElement(e,"content previewcolcontent");
f.f=new Similitude.TabPanels;var l;k=function(a){return function(){window.downloadCallbacks[a]({configCode:f.Q0(a),currentStyleSheetNum:f.A0,filename:0===a?"DemoTriFoldJS.zip":"DemoGWTriFold.zip"})}};for(d=0;2>d;d++)c=genElement(0,"pane"),h=genElement(c,"previewheader em2"),h.innerHTML="Code to add triFold to your page with this configuration.",h=genElement(c,"codewindow"),f.E0[d]=genElement(h,"codewindow-inner"),l=genElement(c,"downloadsection"),g=genElement(l,"iconwrapper"),h=genElement(g,"downloadicon"),
addSvg(h,"download","",0),genElement(g,"language").innerHTML=0===d?"js":"GWT",g=genElement(l,"infowrapper"),g=genElement(g,"downloadinfo"),g.innerHTML="Download a fully functional demo that uses the configurations you've set on this page.",h.addEventListener("click",k(d)),h=document.createElement("span"),h.innerHTML=0===d?"JS":"GWT",h.className="em1",f.f.appendPanel(c,h);e.appendChild(f.f.getElement());f.f._widthChanged();f.L=new Similitude.PushButton;f.L.setEnabled(!1);f.L.getElement().className+=
" reloadBehaviorButton";f.a(b);f.A(f.A0);var m=Similitude.fixedLineTool;f.f.setOnChange(function(){m.rescan(!1)});f.c0.setOnChange(function(){m.rescan(!1)});a.addScaleCallback(function(a){m.scaleCallback(a)});f.d0()}ConfigDemoJS.StyleSelector=function(){};ConfigDemoJS.BooleanOpt=function(a,b){this.B1=genElement(0,"checkboxFrame");this.P=new Similitude.ToggleDiv(a);this.P.setDown(a);0!==b&&this.P.setOnClick(b)};ConfigDemoJS.BooleanOpt.prototype={W:function(){return this.B1}};
var getVariantsArrow=function(a,b){return[[a,b,"active brightbg",0,0],[a,b,"inactive brightbg","inactivebrightbg",function(a){SVGTools.replaceStyle(a,["path"],"stroke","#999999");SVGTools.replaceStyle(a,["path"],"fill","#999999")}],[a,b,"active darkbg","activedarkbg",function(a){SVGTools.replaceStyle(a,["path"],"stroke","#bcd0d0");SVGTools.replaceStyle(a,["path"],"fill","#bcd0d0")}],[a,b,"inactive darkbg","inactivedarkbg",function(a){SVGTools.replaceStyle(a,["path"],"stroke","#808080");SVGTools.replaceStyle(a,
["path"],"fill","#808080")}]]};
ConfigDemoJS.DoubleOptInfo=function(a,b,d,c,e){var f=this;f.T=!0;f.J0=a;f.I=a;f._0=b;f.e0=d;f.V0=c;f.g0=e;f.O=new Similitude.PushButton;f.O.getElement();f.O.getElement().className+=" incr";f.O.setEnabled(a<f.e0);f.O.setOnClick(function(){f.g(f.J0+f.V0,!0)});svgInjector.addSvgVariants(f.O.getFace(),getVariantsArrow("arrow-21_up",0));f.M=new Similitude.PushButton;f.M.getElement().className+=" decr";f.M.setEnabled(a>f._0);f.M.setOnClick(function(){f.g(f.J0-f.V0,!0)});svgInjector.addSvgVariants(f.M.getFace(),getVariantsArrow("arrow-21_down",
0));f.G0=function(){};f.C1=document.createElement("input");f.C1.value=a;f.C1.setAttribute("type","text");f.C1.addEventListener("keydown",function(a){f.N(a)});f.C1.addEventListener("blur",function(){f.g(parseFloat(f.C1.value),!1)});f.C1.className="double-entry"};
ConfigDemoJS.DoubleOptInfo.prototype={N:function(a){var b=a.charCode||a.keyCode;8==b||9==b||46==b||110==b||this.T&&190==b||35<=b&&40>=b||48<=b&&57>=b||96<=b&&105>=b||a.preventDefault()},_1:function(){return this.J0==this.I},J:function(){return this.J0},g:function(a,b){consoleLog("doubleOptInfo "+this.g0+" value change to "+floatFmt(a)+" from button? "+b.toString());if(a!==this.J0){var d=!0,c=!1;a>this.J0?(this.J0==this._0&&this.M.setEnabled(!0),this.J0==this.e0?d=!1:a>=this.e0?(c=!0,this.J0=this.e0,
this.O.setEnabled(!1)):this.J0=a):(this.J0==this.e0&&this.O.setEnabled(!0),this.J0==this._0?d=!1:a<=this._0?(c=!0,this.J0=this._0,this.M.setEnabled(!1)):this.J0=a);if(c||d&&b)this.C1.value=this.J0;this.G0()}},i0:function(a){this.T=!a},Q:function(a){this.g(a,!0)}};
ConfigDemoJS.DoubleOpt=function(a,b,d){this.j=a;this.B1=genElement(0,"double-opt "+b+(1==a.length)?" double-row":" multi-double-row");for(b=0;b<this.j.length;b++)this.j[b].G0=d,a=genElement(this.B1,"entry-panel"),genElement(a,"entry-label em1").innerHTML=this.j[b].g0,a.appendChild(this.j[b].O.getElement()),a.appendChild(this.j[b].C1),a.appendChild(this.j[b].M.getElement())};
ConfigDemoJS.DoubleOpt.prototype={W:function(){return this.B1},X:function(){for(var a=[],b=0;b<this.j.length;b++)a.push(this.j[b].J());return a},_1:function(){for(var a=0;a<this.j.length;a++)if(!this.j[a]._1())return!1;return!0},L0:function(){return!0},Y:function(a){for(var b=this.X(),d=(a?"[":"new double[]{")+floatFmt(b[0]),c=1;c<b.length;c++)d+=", "+floatFmt(b[c]);return d+(a?"]":"}")}};ConfigDemoJS.BehaviorNet=function(){};
ConfigDemoJS.ModeOpt=function(a,b,d){var c=this;c.J0=a;c.I=a;c.b0=new Similitude.SelectBox;c.b0.appendStr("Fixed");c.b0.appendStr("Slide");c.b0.appendStr("Minimize");c.b0.selectIndex(a);c.b0.addedToDom();c.B1=genElement(0,"modeOpt dropDownRow");c.B1.appendChild(c.b0.getElement());c.b0.setOnChangeCallback(function(){c.e()});c.K0=b;c.G0=d};
ConfigDemoJS.ModeOpt.prototype={h0:function(){return["ModeAll:[Behavior."+window.MODE_CONSTS[this.J0]+"]","behavior.setModeAll(DefaultBehavior."+window.MODE_CONSTS[this.J0]+");"]},W:function(){return this.B1},J:function(){return this.J0},L0:function(){return!0},_1:function(){return this.J0==this.I},e:function(){var a=this.b0.getSelectedIndex(),b=0!==a;this.K0.secondVisOpt.setMode(a);this.K0.rolloverOpt.setEnabled(b);this.K0.thirdVisOpt.setMode(a);this.K0.thirdOrderedOpt.setEnabled(2==a);this.J0=a;
this.G0()},Q:function(a){this.J0=a;this.b0.selectIndex(a)},j0:function(a){for(var b=0;3>b;b++)a.setMode(b,this.J0)}};ConfigDemoJS.FirstLayoutOpt=function(a,b,d){var c=this;c.J0=a;c.I=a;c.b0=new Similitude.SelectBox;c.b0.appendStr("Left");c.b0.appendStr("Center");c.b0.appendStr("Right");c.b0.selectIndex(a);c.b0.addedToDom();c.B1=genElement(0,"firstLayoutOpt dropDownRow");c.B1.appendChild(c.b0.getElement());c.b0.setOnChangeCallback(function(){c.e()});c.K0=b;c.G0=d};
ConfigDemoJS.FirstLayoutOpt.prototype={h0:function(){return["DefaultOneCol:[TriFold."+window.COL_CONSTS[this.J0]+"]","behavior.setDefaultOneCol(GWTriFold"+window.COL_CONSTS[this.J0]+");"]},W:function(){return this.B1},J:function(){return this.J0},L0:function(){return!0},_1:function(){return this.J0==this.I},e:function(){this.J0=this.b0.getSelectedIndex();this.G0()},Q:function(a){this.J0=a;this.b0.selectIndex(a)},j0:function(a){a.setDefaultOneCol(this.J0)}};
ConfigDemoJS.SecondLayoutOpt=function(a,b,d){var c=this;c.b=3;c.A1=[3,3];c.X0=[];c.B1=genElement(0,"secondlayoutopt dropDownRow");for(var e,f=function(a){return function(){c.d(a)}},k=0;2>k;k++)e=new Similitude.SelectBox,e.appendStr("Left"),e.appendStr("Center"),e.appendStr("Right"),k<a.length&&(c.A1[k]=a[k]),e.selectIndex(c.A1[k]),e.addedToDom(),e.setOnChangeCallback(f(k)),c.B1.appendChild(e.getElement()),c.X0.push(e);c.C0=c.H0();c.K0=b;c.G0=d};
ConfigDemoJS.SecondLayoutOpt.prototype={h0:function(){for(var a=this.H0(),b=["DefaultTwoCol:[[","behavior.setDefaultTwoCol(new int[] {"],d=0;d<a.length;d++)b[0]+=(1==d?", ":"")+"TriFold."+window.COL_CONSTS[a[d]],b[1]+=(1==d?", ":"")+"GWTriFold."+window.COL_CONSTS[a[d]];b[0]+="]]";b[1]+="});";return b},W:function(){return this.B1},Z0:function(){return this.A1.slice(0)},L0:function(){return!0},_1:function(){var a=this.H0();if(a.length!==this.C0.length)return!1;for(var b=0;b<a.length;b++)if(this.C0[b]!==
a[b])return!1;return!0},d:function(a){var b=this.X0[a].getSelectedIndex(),d=this.A1[a];this.A1[a]=b;this.A1[1-a]==b&&(this.A1[1-a]=3==b||3==this.A1[a]?(b+1)%3:d,this.X0[1-a].selectIndex(this.A1[1-a]));this.K0.secondVisOpt.H();this.G0()},F:function(a){if(!(1>a.length||2<a.length))for(var b=0;2>b;b++)b>=a.size()&&a.push(3),a[b]!==this.A1[b]&&this.X0.selectIndex(a[b])},H0:function(){for(var a=[],b=0;2>b;b++)3!==this.A1[b]&&a.push(this.A1[b]);return a},j0:function(a){a.setDefaultTwoCol(this.H0())}};
ConfigDemoJS.SecondVisOpt=function(a,b,d,c){var e=this;e.B1=genElement(0,"checkboxrow secondVisOpt");e.A1=a;e.R0=[];e.Y0=[!0,!0];e.K0=d;e.G0=c;d=function(a){return function(){e.P0(a)}};for(c=0;2>c;c++)e.R0[c]=new Similitude.ToggleDiv(a[c]),e.R0[c].setOnClick(d(c)),e.B1.appendChild(e.R0[c].getElement());e.setMode(b);e.C0=e.D1()};
ConfigDemoJS.SecondVisOpt.prototype={H:function(){this.setMode(this.V)},h0:function(){if(!this.Y0[0]&&!this.Y0[1])return["",""];for(var a=["VisTwoCol:[[","behavior.setVisTwoCol(new int[]{"],b=this.D1(),d=0;d<b.length;d++)a[0]+=(1==d?", ":"")+"TriFold."+window.COL_CONSTS[b[d]],a[1]+=(1==d?", ":"")+"GWTriFold."+window.COL_CONSTS[b[d]];a[0]+="]]";a[1]+="});";return a},W:function(){return this.B1},L0:function(){return this.V!==TriFold.DefaultBehavior.FIXED},_1:function(){var a=this.D1();if(a.length!==
this.C0.length)return!1;for(var b=0;b<a.length;b++)if(-1==this.C0.indexOf(a[b]))return!1;return!0},P0:function(a){this.A1[a]=this.R0[a].isDown();a=this.Y0[0]&&this.A1[0]?1:0+(this.Y0[1]&&this.A1[1])?1:0;this.K0.rolloverOpt.setEnabled(1==a||0===a&&this.V==TriFold.DefaultBehavior.SLIDE);this.setMode(this.V);this.G0()},D:function(a,b,d){this.R0[0].setEnabled(a);this.R0[1].setEnabled(b);this.Y0=[a,b];a=this.Y0[0]&&this.A1[0]?1:0+(this.Y0[1]&&this.A1[1])?1:0;this.K0.rolloverOpt.setEnabled(1==a||0===a&&
d==TriFold.DefaultBehavior.SLIDE)},setMode:function(a){if(a==TriFold.DefaultBehavior.FIXED)this.D(!1,!1,a);else{var b=this.K0.secondLayoutOpt.Z0();3>b[0]&&3==b[1]?(this.V!==a&&(this.A1[1]=!1),this.D(!0,!1,a)):3===b[0]&&3>b[1]?(this.V!=a&&(this.A1[0]=!1),this.D(!1,!0,a)):a==TriFold.DefaultBehavior.SLIDE?this.D(!0,!0,a):this.A1[0]?this.D(!0,!1,a):this.A1[1]?this.D(!1,!0,a):this.D(!0,!0,a)}this.V=a},D1:function(){for(var a=[],b=this.K0.secondLayoutOpt.Z0(),d=0;2>d;d++)this.A1[d]&&this.Y0[d]&&a.push(b[d]);
return a},j0:function(a){a.setVisTwoCol(this.D1())}};ConfigDemoJS.RolloverOpt=function(a,b,d){var c=this;c.J0=a;c.I=a;c.B1=genElement(0,"checkboxrow rollover");c.P=new Similitude.ToggleDiv(a);c.B1.appendChild(c.P.getElement());c.Y0=!0;c.P.setOnChange(function(){c.O0()});c.K0=b;c.G0=d};
ConfigDemoJS.RolloverOpt.prototype={h0:function(){return["RolloverTwoCol:[Behavior."+window.ROLLOVER_CONSTS[this.J0?1:0]+"]","behavior.setRolloverTwoCol(DefaultBehavior."+window.ROLLOVER_CONSTS[this.J0?1:0]+");"]},W:function(){return this.B1},Z:function(){return this.J0},L0:function(){return this.Y0},_1:function(){return this.J0==this.I},C:function(a){this.P.setDown(a)},setEnabled:function(a){this.P.setEnabled(a);this.Y0=a},O0:function(){this.J0=this.P.isDown();this.G0()},j0:function(a){a.setRolloverTwoCol(this.Y0&&
this.value?1:0)}};ConfigDemoJS.ThirdVisOpt=function(a,b,d,c){var e=this;e.B1=genElement(0,"checkboxrow thirdvis");e.V=b;e.A1=a;e.R0=[];e.Y0=[!0,!0,!0];b=function(a){return function(){e.H1(a)}};for(var f=0;3>f;f++)e.R0.push(new Similitude.ToggleDiv(a[f])),e.R0[f].setOnClick(b(f)),e.B1.appendChild(e.R0[f].getElement());e.K0=d;e.G0=c;e.C0=e.D1()};
ConfigDemoJS.ThirdVisOpt.prototype={h0:function(){if(-1===this.Y0.indexOf(!0))return["",""];for(var a=["VisThreeCol:[[","behavior.setVisThreeCol(new int[]{"],b=this.D1(),d=0;d<b.length;d++)a[0]+=(1<=d?", ":"")+"TriFold."+window.COL_CONSTS[b[d]],a[1]+=(1<=d?", ":"")+"GWTriFold."+window.COL_CONSTS[b[d]];a[0]+="]]";a[1]+="});";return a},W:function(){return this.B1},D:function(a,b,d){this.Y0=[a,b,d];for(a=0;3>a;a++)this.R0[a].setEnabled(this.Y0[a])},L0:function(){return this.V==TriFold.DefaultBehavior.CAN_MINIMIZE},
_1:function(){var a=this.D1();if(a.length!==this.C0.length)return!1;for(var b=0;b<a.length;b++)if(-1==this.C0.indexOf(a[b]))return!1;return!0},setMode:function(a){a==TriFold.DefaultBehavior.FIXED||a==TriFold.DefaultBehavior.SLIDE?this.D(!1,!1,!1):this.A1[0]&&this.A1[1]?(this.A1[2]=!1,this.D(!0,!0,!1)):this.A1[0]&&this.A1[2]?this.D(!0,!1,!0):this.A1[1]&&this.A1[2]?this.D(!1,!0,!0):this.D(!0,!0,!0);this.V=a},H1:function(a){this.A1[a]=this.R0[a].isDown();this.setMode(this.V);this.G0()},D1:function(){for(var a=
[],b=[TriFold.LEFT,TriFold.CENT,TriFold.RIGHT],d=0;3>d;d++)this.A1[d]&&this.Y0[d]&&a.push(b[d]);return a},j0:function(a){a.setVisThreeCol(this.D1())}};ConfigDemoJS.ThirdOrderedOpt=function(a,b,d){var c=this;c.B1=genElement(0,"checkboxrow thirdordered");c.J0=a;c.I=a;c.P=new Similitude.ToggleDiv(a);c.P.setOnClick(function(){c.N0()});c.B1.appendChild(c.P.getElement());c.Y0=!0;c.K0=b;c.G0=d};
ConfigDemoJS.ThirdOrderedOpt.prototype={h0:function(){return this.Y0?["OrderedThreeCol:["+this.J0.toString()+"]","behavior.setOrderedThreeCol("+this.J0.toString()+");"]:["",""]},W:function(){return this.B1},Z:function(){return this.J0},L0:function(){return this.Y0},_1:function(){return this.J0==this.I},N0:function(){this.J0=this.P.isDown();this.G0()},C:function(a){this.J0=a;this.P.setDown(a)},setEnabled:function(a){this.P.setEnabled(a);this.Y0=a},j0:function(a){this.Y0&&a.setOrderedThreeCol(this.J0)}};
ConfigDemoJS.StyleSelector=function(a,b,d){var c=this;c.U=genElement(0,"styleSelector");var e=function(a){return function(){c.E(a)}};c.M0=d;c.f0=[];for(var f=0;f<a.length;f++)d=new Similitude.PushButton,d.setOnClick(e(f)),d.getFace().innerHTML=a[f],c.U.appendChild(d.getElement()),c.f0.push(d);c.f0[b].setEnabled(!1)};ConfigDemoJS.StyleSelector.prototype={getElement:function(){return this.U},E:function(a){this.M0(a);for(var b=0;b<this.f0.length;b++)this.f0[b].setEnabled(b!==a)}};
ConfigDemoJS.prototype={A:function(a){var b=this.i.getElement();3==a?(b.className=classListRemove(b.className,"brightbgarea"),b.className+=" darkbgarea"):(b.className=classListRemove(b.className,"darkbgarea"),b.className+=" brightbgarea");for(b=1;4>b;b++)document.styleSheets[b].disabled=a+0==b?!1:!0;1==a?(this.c0.setSquareMode(!0),this.f.setSquareMode(!0)):(this.c0.setSquareMode(!1),this.f.setSquareMode(!1));this.A0=a},Q0:function(a){a=this.E0[a].innerHTML;a=a.replace(/((<br>)?\s*<br\s*\/>|<br>)\s*}[^}]*$/,
"\n\t}");a=a.replace(/(<br>)?\s*<br\s*\/>/g,"\n\t\t");a=a.replace(/<br>/g,"\n\t\t");a=a.replace(/<\/?div>/g,"\n\t\t");a=a.replace(/<div\s+class=['"]longindent['"]\s*>/g,"\n\t\t\t\t");a=a.replace(/<div\s+class=['"]indent['"]\s*>/g,"\n\t\t\t");return"\n\t"+a},d0:function(){consoleLog("refresh called!");var a,b,d,c=[[],[]],e=[this.E1,this.I0],f=[this.S0,this.i];for(d=0;2>d;d++)for(a=0;a<e[d].length;a++)e[d][a].j0(f[d]),e[d][a].L0()&&!e[d][a]._1()&&c[d].push(e[d][a].h0());d=function(a,d){var c="";for(b=
0;b<a.length;b++)c+=(d==JS&&0<b&&b+1<=a.length?",":"")+(0<b?"<br/>":"")+(0<b&&d==JS?"\t":"")+a[b][d];return c};for(a=0;2>a;a++)e=CODE_SAMPLE[a].HAS_ARGS,this.E0[a].innerHTML=CODE_SAMPLE[a].PREFACE+(0<c[0].length?e[0][0]+d(c[0],a,console)+e[0][1]:"")+CODE_SAMPLE[a].MIDPOINT+(0<c[1].length?e[1][0]+d(c[1],a,console)+e[1][1]:"")+CODE_SAMPLE[a].SUFFIX;this.i.redraw()},a:function(a){var b,d,c,e=this;d=function(){e.d0()};var f=function(){e.L.setEnabled(!0);e.d0()},k=new Similitude.TabPanels;e.c0=k;var h=
genElement(0,"visualconfig"),g=ConfigDemoJS.DoubleOptInfo,l=ConfigDemoJS.DoubleOpt,m=function(a,b,d){genElement(a,"label "+b).innerHTML=d};c=function(a,b,d,c,f){a=genElement(a,b);0!==d&&m(a,"em2",d);a.appendChild(c.W());f?e.I0.push(c):e.E1.push(c)};m(h,"em2","Pick an example stylesheet for your demo:");pickstyleCallback=function(a){e.A(a+1)};b=new ConfigDemoJS.StyleSelector(["one","two","three"],0,pickstyleCallback);h.appendChild(b.getElement());m(h,"em2","Customize the proportions of your app");
b=e.i.getMinColDimensions();window.changedMinColRes(b);b=new l([new g(b[0],240,480,10,"X"),new g(b[1],360,720,10,"Y")],"",d);b.h0=function(){return["MinColDimensions:["+this.Y(!0)+"]","triFold.setMinColDimensions("+this.Y(!1)+");"]};b.j0=function(a){var b=this.X();window.changedMinColRes(b);a.setMinColDimensions(b);e.f._widthChanged();e.c0._widthChanged()};c(h,"mincolres","column dimensions",b,!0);b=e.i.getColSpacing();b=new l([new g(b,0,150,4,"")],"",d);b.h0=function(){var a=this.j[0].J().toString();
return["ColSpacing:["+a+"]","triFold.setColSpacing("+a+");"]};b.j0=function(a){a.setColSpacing(this.j[0].J())};c(h,"colspacing","column spacing",b,!0);b=e.i.getMargins();b=new l([new g(b[0],0,250,10,"N"),new g(b[1],0,350,10,"E"),new g(b[2],0,250,10,"S"),new g(b[3],0,350,10,"W")],"",d);b.h0=function(){return["Margins:["+this.Y(!0)+"]","triFold.setMargins("+this.Y(!1)+");"]};b.j0=function(a){a.setMargins(this.X())};c(h,"margins","margins",b,!0);b=e.i.getPadding();d=new l([new g(b[0],0,250,10,"N"),new g(b[1],
0,350,10,"E"),new g(b[2],0,250,10,"S"),new g(b[3],0,350,10,"W")],"",d);d.h0=function(){return["Padding:["+this.Y(!0)+"]","triFold.setPadding("+this.Y(!1)+");"]};d.j0=function(a){a.setPadding(this.X())};c(h,"padding","padding",d,!0);c=document.createElement("span");c.innerHTML="Appearance";c.className="em1";k.appendPanel(h,c);h=genElement(0,"behaviorconfig");c=new ConfigDemoJS.BehaviorNet;c.firstLayoutOpt=new ConfigDemoJS.FirstLayoutOpt(e.S0.getDefaultOneCol(),c,f);c.secondLayoutOpt=new ConfigDemoJS.SecondLayoutOpt(e.S0.getDefaultTwoCol(),
c,f);c.modeOpt=new ConfigDemoJS.ModeOpt(e.S0.getMode(TriFold.DefaultBehavior.TWO_AVAILABLE),c,f);c.rolloverOpt=new ConfigDemoJS.RolloverOpt(e.S0.getRolloverTwoCol(),c,f);c.thirdOrderedOpt=new ConfigDemoJS.ThirdOrderedOpt(e.S0.getOrderedThreeCol(),c,f);g=e.S0.getVisTwoCol();l=e.S0.getDefaultTwoCol();b=[!1,!1];for(d=0;d<l.length;d++)-1!==g.indexOf(l[d])&&(b[d]=!0);c.secondVisOpt=new ConfigDemoJS.SecondVisOpt(b,c.modeOpt.J(),c,f);g=e.S0.getVisThreeCol();l=[!1,!1,!1];b=[TriFold.LEFT,TriFold.CENT,TriFold.RIGHT];
for(d=0;d<b.length;d++)-1!==g.indexOf(b[d])&&(l[d]=!0);c.thirdVisOpt=new ConfigDemoJS.ThirdVisOpt(l,c.modeOpt.J(),c,f);var f=document.createElement("table"),n=function(a){var b=a;if("string"==typeof b||b instanceof String)b=document.createElement("div"),b.className="bhvlabel",b.innerHTML=a;else if(!("notAWidget"in b))return e.E1.push(b),b.W();return b};d=function(a,b,d){for(var c,e,f=document.createElement("tr"),g=0;2>g;g++)e=document.createElement("td"),c=n(d[g]),e.appendChild(c),f.appendChild(e);
f.className=b;a.appendChild(f)};g=function(a,b,d){var c=document.createElement("tr"),e=document.createElement("td");e.setAttribute("colspan","2");e.appendChild(n(d));c.appendChild(e);c.className=b;a.appendChild(c)};d(f,"modeopt",["column movement",c.modeOpt]);g(f,"colsavail em2","one column available");d(f,"firstlayoutopt",["Initial Layout",c.firstLayoutOpt]);g(f,"colsavail em2","two columns available");d(f,"secondlayoutopt",["Initial Layout",c.secondLayoutOpt]);d(f,"secondvisopt",["always visible?",
c.secondVisOpt]);d(f,"rolloveropt",["fold over",c.rolloverOpt]);g(f,"colsavail em2","three columns available");g=genElement(0,"colnames");m(g,"left","left");m(g,"center","center");m(g,"right","right");g.notAWidget=!0;d(f,"thirdlayout",["Initial Layout",g]);d(f,"thirdvisopt",["always visible?",c.thirdVisOpt]);d(f,"thirdorderedopt",["keep L->R order",c.thirdOrderedOpt]);h.appendChild(f);h.appendChild(e.L.getElement());e.L.getFace().innerHTML=" apply behavior ";e.L.setOnClick(function(){e.i.setBehavior(e.S0);
e.S0=e.S0.copy();e.L.setEnabled(!1)});m(h,"","click this button to reset  the layout as if you just loaded a page with these settings");c=document.createElement("span");c.innerHTML="Behavior";c.className="em1";k.appendPanel(h,c);a.appendChild(k.getElement());k._widthChanged()}};

