var bowser={};
!function(d,f){"function"==typeof define?define(f):"undefined"!=typeof module&&module.exports?module.exports.browser=f():this[d]=f()}("bowser",function(){var d=navigator.userAgent,f=/(msie|trident)/i.test(d),l=/chrome|crios/i.test(d),p=/phantom/i.test(d),u=/safari/i.test(d)&&!l&&!p,n=/iphone/i.test(d),g=/ipad/i.test(d),v=/touchpad/i.test(d),a=/android/i.test(d),b=/opera/i.test(d)||/opr/i.test(d),c=/firefox/i.test(d),e=/gecko\//i.test(d),x=/seamonkey\//i.test(d),h=/version\/(\d+(\.\d+)?)/i,t=/firefox\/(\d+(\.\d+)?)/i,
k,d=f?{name:"Internet Explorer",msie:!0,version:d.match(/(msie |rv:)(\d+(\.\d+)?)/i)[2]}:b?{name:"Opera",opera:!0,version:d.match(h)?d.match(h)[1]:d.match(/opr\/(\d+(\.\d+)?)/i)[1]}:l?{name:"Chrome",webkit:!0,chrome:!0,version:d.match(/(?:chrome|crios)\/(\d+(\.\d+)?)/i)[1]}:p?{name:"PhantomJS",webkit:!0,phantom:!0,version:d.match(/phantomjs\/(\d+(\.\d+)+)/i)[1]}:v?{name:"TouchPad",webkit:!0,touchpad:!0,version:d.match(/touchpad\/(\d+(\.\d+)?)/i)[1]}:n||g?(k={name:n?"iPhone":"iPad",webkit:!0,mobile:!0,
ios:!0,iphone:n,ipad:g},h.test(d)&&(k.version=d.match(h)[1]),k):a?{name:"Android",webkit:!0,android:!0,mobile:!0,version:(d.match(h)||d.match(t))[1]}:u?{name:"Safari",webkit:!0,safari:!0,version:d.match(h)[1]}:e?(k={name:"Gecko",gecko:!0,mozilla:!0,version:d.match(t)[1]},c&&(k.name="Firefox",k.firefox=!0),k):x?{name:"SeaMonkey",seamonkey:!0,version:d.match(/seamonkey\/(\d+(\.\d+)?)/i)[1]}:{};return d.msie&&8<=d.version||d.chrome&&10<=d.version||d.firefox&&4<=d.version||d.safari&&5<=d.version||d.opera&&
10<=d.version?d.a=!0:d.msie&&8>d.version||d.chrome&&10>d.version||d.firefox&&4>d.version||d.safari&&5>d.version||d.opera&&10>d.version?d.c=!0:d.x=!0,d});
var Similitude=function(){var d={},f=function(a,b){var c=document.createElement("div");c.className=b;0!==a&&a.appendChild(c);return c},l=function(a){return parseFloat(a.slice(0,-2))},p=function(a){return"px"==a.slice(-2)?parseFloat(a.slice(0,-2)):a},u=function(a){var b=Math.pow(10,1);return String(Math.round(a*b)/b)},n=function(a,b){return a.replace(RegExp("( "+b+"($|(?= ))|(^|(?= ))"+b+" |^"+b+"$)","g"),"")};window.systemFontsOnly=function(){var a="webkit"in bowser&&bowser.webkit;a&&(document.body.className+=
" systemFontsOnly");return a}();d.bordersScaleWell="webkit"in bowser&&bowser.webkit;d._FixedLineTool=function(){this.items={};this.curscale=1};d._FixedLineTool.prototype={addItem:function(a,b){var c;if(!(a in this.items)){var e=document.getElementsByClassName(a),d=[];for(c=e.length;c--;d.unshift(e[c]));this.items[a]=[d,[]]}for(c=0;c<b.length;c++)this.items[a][1].push(b[c])},rescan:function(a){var b,c;for(b in this.items)if(this.items.hasOwnProperty(b)){var e=document.getElementsByClassName(b),d=[];
for(c=e.length;c--;d.unshift(e[c]));if(a)this.items[b][0]=d;else for(c=0;c<d.length;c++)-1===this.items[b][0].indexOf(d[c])&&this.items[b][0].push(d[c])}this.scaleCallback(this.curscale)},scaleCallback:function(a){var b,c,e,d,h,t,f,g;d=Math.round(a)/a;for(g in this.items)if(this.items.hasOwnProperty(g))for(b=0;b<this.items[g][1].length;b++){e=this.items[g][1][b];f="";t=e[1];for(c=0;c<e[2].length;c++)h=e[2][c],f="string"===typeof h?f+h:t?f+(h*Math.round(a*h*0.8)/(a*h)).toString():f+(d*h).toString();
h=f;for(c=0;c<this.items[g][0].length;c++)this.items[g][0][c].style[e[0]]=h}this.curscale=a}};d.fixedLineTool=new d._FixedLineTool;(function(){var a=d.fixedLineTool;d.bordersScaleWell?a.addItem("sim-listbox",[["margin",!0,[1,"px 0px 0px 0px"]]]):(a.addItem("sim-selectbox",[["padding",!0,[1,"px"]]]),a.addItem("sim-togglediv",[["padding",!0,[1,"px"]]]),a.addItem("sim-listbox",[["padding",!0,["0px ",1,"px ",1,"px ",1,"px "]]]),a.addItem("sim-listbox",[["margin",!0,[1,"px 0px 0px ",-1,"px"]]]))})();d._SVGTools=
function(){this.svgie="msie"in bowser&&bowser.msie;this.displayInline=!("gecko"in bowser&&bowser.gecko);this.svgie||(this._serializer=new XMLSerializer)};d._SVGTools.prototype={cloneSvgNode:function(a){var b=document.createElementNS("http://www.w3.org/2000/svg",a.nodeName),c=a.attributes,e;for(e=0;e<c.length;e++)b.setAttribute(c.item(e).nodeName,c.item(e).nodeValue);for(a=a.firstChild;a;)b.appendChild(1==a.nodeType?this.cloneSvgNode(a):document.createTextNode(a.nodeValue)),a=a.nextSibling;return b},
preprocess:function(a){if(this.displayInline){var b=a.getAttribute("width"),c=a.getAttribute("height");a.hasAttribute("viewBox")||a.setAttribute("viewBox","0 0 "+u(p(b))+" "+u(p(c)));a.setAttribute("x","0px");a.setAttribute("y","0px");a.setAttribute("preserveAspectRatio","xMidYMid")}},replaceStyle:function(a,b,c,e){if("firstChild"in a)for(a=a.firstElementChild;a;)-1<b.indexOf(a.nodeName)&&(a.style[c]=e),this.replaceStyle(a,b,c,e),a=a.nextElementSibling},svgToSerialized:function(a){return this.svgie?
this._xmlSerializeIE(a):this._serializer.serializeToString(a)},serializedToSvg:function(a){var b=document.createElement("div");b.innerHTML=a;return b.firstChild},_xmlSerializeIE:function(a){var b="<"+a.nodeName,c=a.attributes,e;for(e=0;e<c.length;e++)b+=" "+c.item(e).nodeName+"='"+c.item(e).nodeValue+"'";if((c=a.firstChild)&&(c.nextSibling||1==c.nodeType||c.nodeValue.replace(/^\s+|\s+$/g,""))){for(b+=">";c;)b+=1==c.nodeType?this._xmlSerializeIE(c):c.nodeValue,c=c.nextSibling;b+="</"+a.nodeName+">"}else b+=
" />";return b}};d.SVGTools=new d._SVGTools;var g=d.SVGTools;d._SVGInjector=function(){this._svgCache={};this._lazySrcCaching=!0;this.CACHE_MANUAL_ONLY=0;this.CACHE_CROSS_BROWSER=1;this.CACHE_MOD_SRCS=2;this.CACHE_MODS=3;this.CACHE_ALL=4;this._cacheLevel=this.CACHE_MODS;this._cacheMods=!0};d._SVGInjector.prototype={addSvgCached:function(a,b,c,e,d,h){var f=document.createElement("div");this.setSvgCached(f,b,c,e,d,h);a.appendChild(f)},addSvgVariants:function(a,b){for(var c,e=0;e<b.length;e++)c=b[e],
this.addSvgCached(a,c[0],c[1],c[2],c[3],c[4])},addSvgVariantsBright:function(a,b,c,e){this.addSvgVariants(a,[[b,c,e+" brightbg","",0],[b,c,e+" darkbg","darkbg",function(a){g.replaceStyle(a,["path"],"stroke","#FFFFFF");g.replaceStyle(a,["path"],"fill","#FFFFFF")}]])},getCacheLevel:function(){return this._cacheLevel},preloadSvgCache:function(a){var b,c=document.getElementById("svgcargo");for(b=c.firstElementChild;b;)this._svgCache[b.className]=b.firstChild,g.preprocess(this._svgCache[b.className]),
b=b.nextElementSibling;a&&c.parentNode.removeChild(c)},setCacheLevel:function(a){this._cacheLevel=a},setSvgCached:function(a,b,c,e,d,h){var f=g.displayInline;a.className+=(f?" svginline":" svgbg")+" svg "+e;e=this._svgCache;var k=!1===c||""===c||0===c,l="string"===typeof c&&0<c.length,w="object"===typeof c,q="string"===typeof d&&0<d.length,m,n=!1,s=!1,r,p=!0;w&&g.preprocess(c);b in e||(l&&(f||q)?(m=g.serializedToSvg(c),g.preprocess(m),this._cacheLevel>=this.CACHE_MOD_SRC&&q||this._cacheLevel>=this.CACHE_CONVERSION&&
f?e[b]=m:p=!1):w&&(g.preprocess(c),q&&(this._cacheLevel>=this.CACHE_MOD_SRC&&q||this._cacheLevel==this.CACHE_ALL)&&(e[b]=c)));if(!(f||b+"_serialized"in e))if(l&&this._cacheLevel==this.CACHE_ALL)e[b+"_serialized"]=c;else if(!l&&!q){if(k&&!(b in e))return!1;r=g.svgToSerialized(k?e[b]:c);s=!0;this._cacheLevel>=this.CACHE_CONVERSION&&(e[b+"_serialized"]=r)}if(q&&b+d in e)f?m=e[b+d]:(r=e[b+d],s=!0),n=!0;else if(b in e)m=e[b];else{if(k)return!1;w&&(m=c)}q&&!n||f?p&&(m=g.cloneSvgNode(m)):s||(r=l?c:e[b+"_serialized"],
s=!0);q&&!n&&(h(m),this._cacheLevel>=this.CACHE_MODS&&(e[b+d]=f?g.cloneSvgNode(m):g.svgToSerialized(m),f||(r=e[b+d],s=!0)));f?a.appendChild(m):(s||(r=g.svgToSerialized(m)),b="url('data:image/svg+xml,"+encodeURIComponent(r)+"')",a.style.backgroundImage=b)}};d.svgInjector=new d._SVGInjector;var v=d.svgInjector;d.PushButton=function(){var a=this;a._elem=f(0,"sim-pushbutton sim-pushbutton-enabled");a._enabled=!0;a._onclick=function(){};a._onclickWrapper=function(){a._onclick()};a._afill=document.createElement("a");
a._face=f(a._afill,"sim-pushbutton-face");a._afill.setAttribute("href","#");a._elem.appendChild(a._afill);a._afill.addEventListener("click",a._onclickWrapper)};d.PushButton.prototype={getEnabled:function(){return this._enabled},getElement:function(){return this._elem},getFace:function(){return this._face},setEnabled:function(a){a!=this._enabled&&(this._enabled=a,this._elem.className=n(this._elem.className,"sim-pushbutton-"+(a?"disabled":"enabled")),this._elem.className+=" sim-pushbutton-"+(a?"enabled":
"disabled"),this._elem.removeChild(this._elem.firstChild),a?(this._elem.appendChild(this._afill),this._afill.appendChild(this._face)):(this._afill.removeChild(this._face),this._elem.appendChild(this._face)))},setOnClick:function(a){this._onclick=a}};d.ToggleDiv=function(a){var b=this;b._elem=f(0,"");b._afill=document.createElement("a");b._afill.setAttribute("href","#");b._afill.className="sim-togglediv-afill";b._elem.appendChild(b._afill);b._facebg=f(b._afill,"sim-togglediv-facebg");b._face=f(b._facebg,
"sim-togglediv-face");b._down=a;b._enabled=!0;b._writeClass();b._onClick=function(){};b._onChange=function(){};b._onClickWrapper=function(){b.setDown(!b._down);b._onClick()};v.addSvgVariantsBright(b._face,"toggleDiv",d.ToggleDiv.CheckmarkSvgStr,"");b._afill.addEventListener("click",b._onClickWrapper)};d.ToggleDiv.SvgEl=0;d.ToggleDiv.prototype={getElement:function(){return this._elem},getFace:function(){return this._face},isDown:function(){return this._down},setDown:function(a){this.setDownSilent(a)&&
this._onChange()},_writeClass:function(){this._elem.className="sim-togglediv "+(this._down?" sim-togglediv-down":" sim-togglediv-up")+(this._enabled?" sim-togglediv-enabled":" sim-togglediv-disabled")+(this._enabled?this._down?" sim-togglediv-enabled-down":" sim-togglediv-enabled-up":this._down?" sim-togglediv-disabled-down":" sim-togglediv-disabled-up")+" sim-"+(d.bordersScaleWell?"border":"box")},setEnabled:function(a){this._enabled!=a&&(this._enabled=a,this._writeClass(),this._elem.removeChild(this._elem.firstChild),
a?(this._elem.appendChild(this._afill),this._afill.appendChild(this._facebg)):(this._afill.removeChild(this._facebg),this._elem.appendChild(this._facebg)))},setDownSilent:function(a){if(a==this._down)return!1;this._down=a;this._writeClass();return!0},setOnChange:function(a){this._onChange=a},setOnClick:function(a){this._onClick=a}};d.ToggleDiv.CheckmarkSvgStr='<svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" width="300" height="324.7" viewBox="0 0 300 324.7" xml:space="preserve" overflow="visible" enable-background="new 0 0 300 324.7"><metadata id="metadata1967"><rdf:RDF><cc:Work rdf:about=""><dc:format>image/svg+xml</dc:format> <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>        </cc:Work></rdf:RDF></metadata><defs id="defs1965"/><g transform="matrix(0.73874711,0,0,0.73874711,43.063663,38.33353)"><path d="M 0,223.7 C 0,213.3 6.9,204 20.8,196 c 9.2,-4.6 16.2,-6.9 20.8,-6.9 5.8,1.2 9.8,4.6 12.1,10.4 6.9,16.2 11.6,27.2 13.9,32.9 2.3,4.6 4.6,6.9 6.9,6.9 2.3,0 4.6,-1.7 6.9,-5.2 C 120.7,164.7 156,111 187.2,72.8 211.5,43.9 226.5,27.1 232.3,22.5 250.9,8.7 272.8,1.2 298.3,0 l 1.7,8.7 c -19.7,19.7 -53.8,63.6 -102.3,131.8 -47.4,68.2 -81.5,122 -102.3,161.3 -4.6,10.3 -10.4,16.7 -17.4,19 -3.5,3.5 -11,4.6 -22.5,3.5 -8.1,1.2 -13.9,0 -17.3,-3.5 -3.5,-2.3 -6.9,-6.9 -10.4,-13.9 C 16.2,279.2 7.6,255.5 1.8,235.8 1.7,231.2 1.2,227.2 0,223.7 z"/></g></svg>';
d.TabPanels=function(a){this.elem=document.createElement("div");this.elem.className="sim-tabpanels";this._squareMode=!1;this.header=f(this.elem,"sim-header");this.tabRow=f(this.header,"sim-tabrow sim-tabrowheader");this.headerTabGroup=f(this.tabRow,"sim-tabgroup sim-headertabgroup");this.panelBoundary=f(this.elem,"sim-panelboundary");this.panelSpace=f(this.panelBoundary,"sim-panelspace");this.footer=f(this.elem,"sim-footer");this.tabRowFooter=f(0,"sim-tabrow sim-tabrowfooter");this.footerTabGroup=
f(this.tabRowFooter,"sim-tabgroup sim-footertabgroup");this._Panel=function(a,c){this.content=a;this.tab=c;this.tabBoxes=[];this.tabBoxContents=[];this.tabBoxHundred=[];for(var e=this.ctrval=0;2>e;e++)this.tabBoxes.push(document.createElement("div")),this.tabBoxes[e].className="sim-tab sim-tabunselected",this.tabBoxHundred.push(document.createElement("div")),this.tabBoxHundred[e].className="sim-tabHundred",this.tabBoxContents.push(document.createElement("div")),this.tabBoxContents[e].className="sim-tabContents",
this.tabBoxHundred[e].appendChild(this.tabBoxContents[e]),this.tabBoxes[e].appendChild(this.tabBoxHundred[e]),this.tabBoxContents[e].appendChild(0===e?c:c.cloneNode(!0))};this._Panel.prototype.clean=function(){for(var a=this.tabBoxes,c=0;2>c;c++)for(;a[c].hasChildNodes();)a[c].removeChild(a[c].firstChild)};this._tabGroups=[this.headerTabGroup,this.footerTabGroup];this._fancyBorders=[this.headerLine,this.footerLine];this.lineComponents=[[],[]];this._panels=[];this._onSelect=function(){};this._onChange=
function(){};this._addedToDom=!0;this._width=a;this._currentPanel=-1;this._dispFancyBorder=[!0,!1];this._dispTabs=[!0,!1];for(a=this._ctr=0;2>a;a++)this.lineComponents[a]=[f(0,"leftOfSelected"),f(0,"underSelected"),f(0,"rightOfSelected")]};d.TabPanels.prototype={appendPanel:function(a,b){this.insertPanel(this._panels.length,a,b)},clear:function(){var a;for(a=0;a<this._panels.length;a++)this._panels[a].clear();this._panels=[];for(a=0;2>a;a++)for(;this._tabGroups[a].firstChild;)this._tabGroups[a].removeChild(this._tabGroups[a].firstChild);
this.panelSpace.removeChild(this.panelSpace.firstChild)},displayFancyBorders:function(a,b){var c=!1,e,d,h=[a,b];for(e=0;2>e;e++)if(h[e]!==this._dispFancyBorder[e]){var f=this._panels[this._currentPanel].tabBoxes[e];if(h[e])for(c=!0,d=0;3>d;d++)this.lineComponents[e][d].style.visibility="hidden",f.appendChild(this.lineComponents[e][d]);else for(;!f.firstChild.isEqualNode(f.lastChild);)f.removeChild(f.lastChild)}this._dispFancyBorder=h;c&&this._widthChanged()},displayTabRow:function(a,b){if(!a&&!b)return!1;
var c,e,d=!1,f=[this.header,this.footer],g=[this.tabRow,this.tabRowFooter],k=[a,b];for(c=0;2>c;c++)if(this._dispTabs[c]!==k[c])if(k[c]){if(this._dispFancyBorder[c])for(d=!0,e=0;3>e;e++)this.lineComponents[c][e].style.visibility="hidden";f[c].appendChild(g[c])}else f[c].removeChild(g[c]);this._dispTabs=k;d&&this._widthChanged()},getElement:function(){return this.elem},getSelectedIndex:function(){return this._currentPanel},insertPanel:function(a,b,c){var e=this;e._panels.splice(a,0,new e._Panel(b,c));
if(a+1===e._panels.length)for(b=0;2>b;b++)e._tabGroups[b].appendChild(e._panels[a].tabBoxes[b]);else for(b=0;2>b;b++)e._tabGroups[b].insertBefore(e._panels[a].tabBoxes[b],e._panels[a+1].tabBox);e._ctr++;c=e._panels[a].ctrval=e._ctr;var d=function(a){return function(){e._selectCtr(a)}};for(b=0;2>b;b++)e._panels[a].tabBoxes[b].addEventListener("click",d(c));1===e._panels.length?e.selectTabSilent(0):a<=e._currentPanel&&(e._currentPanel+=1,e._widthChanged())},removeTab:function(a){if(!(0>a||a>=this._panels.length)){this._currentPanel===
a&&(1<this._panels.length?this.selectTabSilent(a+1===this._panels.length?a-1:a+1):this.panelSpace.removeChild(this.panelSpace.firstChild));for(var b=0;2>b;b++)this._tabGroups[b].removeChild(this._panels[a].tabBoxes[b]);this._panels[a].clean();this._panels.splice(a,1);this._currentPanel===this.panels.length&&(this._currentPanel=this.panels.length-1,this._widthChanged())}},_selectCtr:function(a){for(var b=0;b<this._panels.length;b++)if(this._panels[b].ctrval===a){this.selectTab(b);break}},selectTab:function(a){this.selectTabSilent(a)&&
this._onChange()},selectTabSilent:function(a){var b,c;if(a===this._currentPanel||0>a||a>=this._panels.length)return!1;this.panelSpace.hasChildNodes()&&this.panelSpace.removeChild(this.panelSpace.firstChild);for(b=0;2>b;b++){if(-1!==this._currentPanel)for(this._panels[this._currentPanel].tabBoxes[b].className="sim-tab sim-tabunselected",c=this._panels[this._currentPanel].tabBoxes[b];!c.firstChild.isEqualNode(c.lastChild);)c.removeChild(c.lastChild);if(this._dispFancyBorder[b]){var e=this._panels[a].tabBoxes[b];
for(c=0;3>c;c++)e.appendChild(this.lineComponents[b][c])}this._panels[a].tabBoxes[b].className="sim-tab sim-tabselected"}this._currentPanel=a;this._widthChanged();this.panelSpace.appendChild(this._panels[a].content);return!0},setOnChange:function(a){this._onChange=a},setOnSelect:function(a){this._onSelect=a},setSquareMode:function(a){if(this._squareMode=a)for(a=0;3>a;a++)this.lineComponents[0][a].style.visibility="hidden";else this._panels[1].tabBoxes[0].style.removeProperty("width");this._widthChanged()},
_widthChanged:function(){if(-1!=this._currentPanel)for(var a,b,c,e,d,f=0;2>f;f++)this._dispFancyBorder[f]&&(a=this._panels[this._currentPanel].tabBoxes[f],b=0===f?this.header:this.footer,b=l(getComputedStyle(b).width),c=l(getComputedStyle(a).width),e=this.lineComponents[f],a=a.offsetLeft-1,this._squareMode?(c=l(getComputedStyle(this._panels[0].tabBoxes[0]).width),e=l(getComputedStyle(this._panels[1].tabBoxes[0]).marginLeft),this._panels[1].tabBoxes[0].style.width=(b-(c+e+this._panels[0].tabBoxes[0].offsetLeft)).toString()+
"px"):(e[0].style.width=a.toString()+"px",e[0].style.marginLeft=(-1*a).toString()+"px",e[0].style.visibility="visible",d=l(getComputedStyle(e[0]).height),e[1].style.marginTop=(-1*d).toString()+"px",e[1].style.visibility="visible",e[2].style.marginTop=(-1*d).toString()+"px",e[2].style.width=(b-(a+c)).toString()+"px",e[2].style.visibility="visible"))}};d.SelectBox=function(){this.elem=document.createElement("div");this.elem.className="sim-selectbox sim-"+(d.bordersScaleWell?"border":"box");this.items=
[];this.dispBg=f(this.elem,"sim-dispbg");this.curBoxEl=f(this.dispBg,"sim-disp");this.btnEl=f(this.curBoxEl,"sim-btn");this.listBoxEl=f(this.elem,"sim-listbox");this.listBoxEl.style.display="none";this.listBoxDisplay=!1;this.newDisplay=!0;this.isAddedToDom=!1;this.selected=-1;this.curnode=this.ctr=0;this.onSelect=function(a){};this.onChange=function(a){};v.addSvgVariantsBright(this.btnEl,"selectbox",d.SelectBox.DropdownSvgStr,"")};d.SelectBox.SvgEl=0;d.SelectBox.prototype={getElement:function(){return this.elem},
setOnSelect:function(a){this.onSelect=a},setOnChangeCallback:function(a){this.onChange=a},addedToDom:function(){var a=this,b=function(){a.listBoxDisplay=!0;if(a.newDisplay){var b=getComputedStyle(a.curBoxEl);a.listBoxEl.style.top=b.height+b.paddingTop+b.paddingBottom}a.listBoxEl.style.display="block"},c=function(){a.listBoxDisplay=!1;window.setTimeout(function(){a.listBoxDisplay||(a.listBoxEl.style.display="none",a.newDisplay=!0)},100)},e=function(){b();for(var c=0;c<a.items.length;c++)a.items[c].setAttribute("data-hover",
c===a.selected?"true":"false");a.newDisplay=!1};a.curBoxEl.addEventListener("mouseover",e);a.curBoxEl.addEventListener("click",e);a.curBoxEl.addEventListener("mouseout",function(){c()});var d,f,g=function(b){return function(){a._selectCtr(b);a._selectCtr(a.items[b].ctr);a.listBoxDisplay=!1;a.listBoxEl.style.display="none"}},k=function(c){return function(){b();for(f=0;f<a.items.length;f++)a.items[f].ctr===a.items[c].ctr?a.items[f].setAttribute("data-hover","true"):a.items[f].setAttribute("data-hover",
"false")}},l=function(a){return function(){c()}};for(d=0;d<a.items.length;d++)e=a.items[d],e.addEventListener("click",g(d)),e.addEventListener("mouseover",k(d)),e.addEventListener("mouseout",l(d));a.isAddedToDom=!0},removeElem:function(a){for(var b=0;b<this.items.length;b++)if(this.items[b]===a)return this.removeIndex(b);return!1},removeIndex:function(a){console.log("remove called");if(a>=this.items.length||0>a)return!1;this.items[a].className=n(this.items[a].className,"sim-row");this.listBoxEl.removeChild(this.items[a]);
var b=!1;this.selected===a?(this.curBoxEl.removeChild(this.items[a]),b=!0):this.selected>a&&(this.selected-=1);this.items.splice(a,1);0<this.items.length&&b?this.selectElement(0):0===this.items.length&&(this.selected=-1);return!0},len:function(){return this.items.length},addItem:function(a){this.insertItem(a,this.items.length)},insertItem:function(a,b){var c=this;a.className=""===a.className?"sim-row":a.className+" sim-row";b===c.items.length?c.listBoxEl.appendChild(a):c.listBoxEl.insertBefore(a,
c.items[b]);c.ctr+=1;var d=c.ctr;a.ctr=c.ctr;var f=function(){c.listBoxDisplay=!1;window.setTimeout(function(){c.listBoxEl.style.display=c.listBoxDisplay?"block":"none"},300)};c.isAddedToDom&&(a.addEventListener("click",function(){c._selectCtr(d);c.listBoxDisplay=!1;c.listBoxEl.style.display="none"}),a.addEventListener("mouseover",function(){for(var b=0;b<c.items.length;b++)c.items[b].ctr==a.ctr?c.items[b].setAttribute("data-hover","true"):c.items[b].setAttribute("data-hover","false");c.listBoxDisplay=
!0;c.listBoxEl.style.display="block"}),a.addEventListener("mouseout",function(){a.setAttribute("data-hover","false");f()}));c.items.splice(b,0,a);-1==c.selected?(c.selectIndex(0),c.selected=0):c.selected+=b<=c.selected?1:0},appendStr:function(a){return this.insertStr(a,this.items.length)},insertStr:function(a,b){var c=document.createElement("div");c.innerHTML=a;this.addItem(c,b);return c},selectIndex:function(a,b){var c=!1;a!=this.selected&&(c=!0,0!==this.curnode&&this.curBoxEl.removeChild(this.curnode),
this.selected=a,this.curnode=this.items[a].cloneNode(!0),this.curnode.className+=" sim-selected",this.curBoxEl.insertBefore(this.curnode,this.btnEl));if(!b&&(this.onSelect(),c))this.onChange()},getSelectedIndex:function(){return this.selected},_selectCtr:function(a){for(var b=0;b<this.items.length;b++)if(this.items[b].ctr==a)return this.selectIndex(b,!1)}};d.SelectBox.DropdownSvgStr='<svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" width="600" height="471" id="svg3051" version="1.1"> <defs id="defs3053"/> <metadata id="metadata3056"> <rdf:RDF> <cc:Work rdf:about=""> <dc:format>image/svg+xml</dc:format> <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/> <dc:title/> </cc:Work> </rdf:RDF> </metadata> <g id="layer1" transform="translate(0,-581.36218)"> <path d="M 54.426933,-44.38965 148.99618,52.073249 243.56543,148.53615 112.74148,182.20407 -18.082462,215.87199 18.172235,85.74117 z" transform="matrix(0.43196572,1.2288534,-1.4582918,0.36400298,417.18586,618.88433)" fill="#241c1c"/> </g> </svg>';
return d}();

var TriFold=function(c,f,g,h){return new new function(c,f,g,h,m){function l(){T&&t.D2(!0)}function q(a){return parseFloat(a.slice(0,-2))}function r(a){return a.toString()+"px"}function U(){V.call(this);if(c.attachEvent)c.attachEvent("onload",void 0);else if(c.onload){var a=c.onload;c.onload=function(){a();(void 0)()}}else c.onload=void 0}function V(){for(var a=function(){return function(){t.D2(!1)}}(),b=0;3>b;b++)x[b].P0&&x[b].F();m.ResizeSensor(n,a)}function A(){}function B(a,b){this.F1=b;this.I2=
0;this.d0=a;this.j1=[];this.f1=[[-1,-1,-1],[-1,-1,-1],[-1,-1,-1]]}function L(){if(this.H1=/Android|webOS|iPhone|iPod|BlackBerry|IEMobile|Opera Mini/i.test(g.userAgent))n.className+=" onPhone"}function M(a,b,e){this.C0=a;this.A1=b;this.F1=e;this.i2=10;this.e0=[240,400];this.K0=[20,30,40,30];this.E=[18,12,15,12];this.I2=0;this.T1=!1;this.K=[0,0]}function D(){this.H3={};this.b2={};this.Y=3}function N(){this.Q2=new D;this._0=new D;this.J2=1;this.K1=this.Z2=0;this.M=this.R0=1;this.P2=[0,0,0];this.E1=[0,
0,0];this.M1=[!1,!1,!1];this.Q0=[!0,!0,!0];this.H0=[!0,!0,!0];this.b=[!1,!1,!1];this.J=[1,1,1];this.C2=[0,0,0];this.Z1=[];this.c0=3;this.C=[1,1,1];this.X2=[y.col0[0],y.col1[0],y.col2[0]];this.M0=y.innerParent[0];this.U2=0;this.Y2=1E3;this.G0=0.5;this.D0=this.X=0;this.P=this.D=1;this.d1=1E3;this.c2=400}function O(a){this.I0=a;this.L0=200;this.V1=!1;this.W0=2E3;this.R2=1E3;this._3=2E3;this.f2=1E3;this.N2=0;this.E3=[];this.c=-2500;this.E0=2500}h=function(a,b,e,d){n=f.createElement("div");a.resetToDefaults();
E=a;P=b;Q=e;R=d;F=m.LayoutManip.prototype;x=[new m.DefaultManip(this,0),new m.DefaultManip(this,1),new m.DefaultManip(this,2)];c.manips=x;y=(new A).G3("tri-fold_",x);G=new N;H=I=new O(G);C=new B(E,H);J=new L;t=new M(n,C,H)};h.prototype={addTo:function(a){n.style.visibility="hidden";a.appendChild(n);this.redraw();n.style.visibility="visible";U.call(this)},redraw:function(){t.D2(!0)},recheckBehavior:function(){C._1()},addScaleCallback:function(a){K.push(a)},disableDefaultScaleCallback:function(a){S=
!a;if(a)for(var b=0;3>b;b++)a=y.colContentPlusBorder[b],a.style.removeProperty("transform"),a.style.removeProperty("-ms-transform"),a.style.removeProperty("-webkit-transform")},getElement:function(){return n},getCol:function(a){return y["col"+a.toString()][0]},setMinColDimensions:function(a){t.e0=a.slice(0);l()},getMinColDimensions:function(){return t.e0.slice(0)},setPadding:function(a){t.E=a.slice(0);l()},getPadding:function(){return t.E.slice(0)},setMargins:function(a){t.K0=a.slice(0);l()},getMargins:function(){return t.K0.slice(0)},
setColSpacing:function(a){t.i2=a;l()},getColSpacing:function(){return t.i2},hide:function(a){n.style.visibility=a?"hidden":"visible"},setSlidespeed:function(a){I.setSlidespeed(a)},getSlidespeed:function(){return I.getSlidespeed()},setBehavior:function(a){E=a;C.setBehavior(a)},setLayoutManip:function(a,b){for(var e=[m.LayoutManip.T,m.LayoutManip.W2,m.LayoutManip.T0],d=0;d<e.length;d++)b.A3(e[d],x[a].h0(e[d]));x[a]=b},getLayoutManip:function(a){return x[a]},simulateButtonPress:function(a,b){C.e(a,b)},
setOpts:function(a){for(var b in a)a.hasOwnProperty(b)&&"set"+b in this&&this["set"+b].apply(this,a[b])}};var n,P,Q,R,y={},G,I,H,C,t,E,S=!0,K=[],z=[!1,!1,!1],x,J,T=!1,F=[];A.prototype={S:function(a,b){for(var e=0;e<b.length;e++)a.style[b[e][0]]=b[e][1]},X1:function(a,b,e){e=f.createElement("div");for(var d=0;d<b.length;d++)b[d]in this.F2||(this.F2[b[d]]=[]),this.F2[b[d]].push(e),b[d]=this.Y1+b[d];e.className=b.join(" ");a.appendChild(e);return e},G3:function(a,b){this.F2={};this.Y1=a;this.S(n,[]);
n.classList.add(a+"outerParent");var e=this.X1(n,["innerParent"],[]),e=this.X1(e,["innerParentRel"],[]),d,c,u,p,f,g;for(d=0;3>d;d++){p="col"+d.toString();p=this.X1(e,[p,"cols"],[]);p=this.X1(p,["colRel"],[]);p=this.X1(p,["colContentPlusBorder"],[]);p=this.X1(p,["colContent"],[]);c=this.X1(p,["switchbar","switchbar"+d.toString()],[]);b[d].P0&&b[d].g0(c,F.B2);f=this.X1(c,["switchbarRel"],[]);for(c=u=0;3>c;c++)d!=c&&(g=this.X1(f,["switchbarBtn","switchbarBtnSide"+u.toString(),"buttonCol"+c.toString()],
[]),b[d].P0&&b[d].e2(g,F.Z0),u++);p.appendChild(0===d?P:1===d?Q:R)}return this.F2}};B.prototype={L1:function(a){a!=this.I2&&(this.d0.onAvailChange(a),this.I2=a,this._1())},e:function(a,b){this.d0.onManipUse(a,b);this._1()},setBehavior:function(a){this.d0=a;this.d0.onAvailChange(this.I2);this._1()},getLayout:function(){return this.j1},_1:function(){var a,b,e,d;e=this.d0.getLayout(this.I2);d=this.d0.getButtonStatus(this.I2);for(a=0;3>a;a++)for(b=0;3>b;b++)d[a][b]!=this.f1[a][b]&&x[a].A3(b,d[a][b]);
this.F1.Z(this.j1,e);this.j1=e;this.f1=d}};L.prototype={L2:function(){return this.H1}};M.prototype={D2:function(a){var b=q(getComputedStyle(this.C0).width),e=q(getComputedStyle(this.C0).height);if(!isNaN(b)&&!isNaN(e)){var d=[b,e];if(a||this.K[0]!=d[0]||this.K[1]!=d[1]){this.K=d;var c=this.K0,u=this.E;if(J.L2())for(c=[1,0,1,0],a=0;4>a;a++)u[a]=0.8*this.E[a];var p=b/e,f=[-1,-1,-1,-1],g=[-1,-1,-1,-1],e=[u[3]+u[1],u[0]+u[2]],h=[c[3]+c[1],c[0]+c[2]];for(a=1;4>a;a++)f[a]=(this.e0[0]*a+e[0]+(a-1)*this.i2+
h[0])/(this.e0[1]+e[1]+h[1]),g[a]=this.e0[0]*a+e[0]+(a-1)*this.i2+h[0];var b=0===h[1]?0.5:c[0]/h[1],c=0===h[0]?0.5:c[3]/h[0],p=p<f[2]||d[0]<g[2]?1:p<f[3]||d[0]<g[3]?p<1.2*f[2]&&(1==this.I2||2==this.I2)?this.I2:2:p<1.2*f[3]&&2<=this.I2?this.I2:3,m=[this.e0[0]*p+e[0]+(p-1)*this.i2,this.e0[1]+e[1]],k=[m[0]+h[0],m[1]+h[1]],f=0,g=[0,0],l=[0,0],f=d[0]<=k[0]||d[1]<=k[1]?1:Math.min(d[0]/k[0],d[1]/k[1]);for(a=0;2>a;a++)d[a]<=k[a]?(g[a]=0,l[a]=1==a||1==p?Math.max(0,d[a]-f*m[a]):f*h[a]):(l[a]=f*h[a],g[a]=d[a]-
f*k[a]);h=[!1,!1,!1];d=d[0]-(l[0]+f*e[0]);if(this.T1)for(this.I2!=p&&this.A1.L1(p),this.I2=p,e=this.A1.getLayout(),a=0;a<e.length;a++)h[e[a]]=!0;G.h2(l,g,f,c,b,d,[f*u[0],f*u[1],f*u[2],f*u[3]],this.e0,f*this.i2,h);this.T1||(this.A1.L1(p),this.I2=p,this.T1=!0)}}}};D.prototype={U0:function(a,b,e,d,c,u,f,h){this.V0=a;this.G1=b;this.G=e;this.V=d;this.L=c;this.g2=u;this.V2=f;this.i0=h;this.N1=[];this.I1=0},d2:function(){for(var a in this.b2)this.b2.hasOwnProperty(a)&&(this.b2[a]=-1)},f:function(a){return this.H3[a][this.b2[a]]},
a:function(a){if(a.id==this.b2[a.V0]){var b=(new Date).getTime(),e=Math.max(0,b-a.L),b=a.G-a.G1,e=e/a.V;1<e&&(e=1);a.g2(a.G1+b*e);if(1>e){var d=this;c.setTimeout(function(){d.a(a)},this.Y)}else a.V2(),delete this.H3[a.V0][a.id],delete this.b2[a.V0]}else a.i0(),delete this.H3[a.V0][a.id]},U1:function(a,b,e,d,c,f,h){b=new this.U0(a,b,e,d,(new Date).getTime(),c,f,h);a in this.b2||(this.b2[a]=0);this.b2[a]=(this.b2[a]+1)%1E3;b.id=this.b2[a];a in this.H3||(this.H3[a]={});this.H3[a][b.id]=b;this.a(b)}};
N.prototype={c1:function(a,b,e){var d={};d.srcs=a;d.tgt=b;d.add=e;if(a[0]==b&&1==a.length)for(e=0;e<this.Z1.length;e++)if(this.Z1[e].tgt==b&&1==this.Z1[e].srcs.length&&this.Z1[e].srcs[0]==a[0]){this.Z1.splice(e,1);break}this.Z1.push(d)},_2:function(a,b){this.X2[a].style.zIndex=b?this.C[a].toString():"-1000";z[a]=b},S2:function(a){for(var b=0;b<this.Z1.length;){var e=this.Z1[b].srcs.indexOf(a);-1<e?(this.Z1[b].srcs.splice(e,1),0===this.Z1[b].srcs.length?(this._2(this.Z1[b].tgt,1==this.Z1[b].add?!0:
!1),this.Z1.splice(b,1)):b++):b++}},D3:function(a,b){for(var e=0;e<this.Z1.length;e++)1==this.Z1[e].srcs.length&&this.Z1[e].srcs[0]==a&&this.Z1[e].tgt!=a&&(this.Z1[e].srcs[0]=b)},h:function(a){for(var b=0;b<this.Z1.length;)this.Z1[b].tgt==a&&this.Z1[b].srcs[0]!=a?this.Z1.splice(b,1):b++},R:function(a){this.M0.style.left=r((this.U2+(this.Y2-a))*this.G0)},setSlidespeed:function(a){this.d1=a},getSlidespeed:function(){return this.d1},h2:function(a,b,e,d,c,f,h,g,m,k){var l=g[0]*e,s=g[1]*e;this.U2=a[0];
this.G0=d;this.Y2=f;this.X=h[3];this.D0=0;this.P=m;var n;for(d=0;3>d;d++)n=y.colContentPlusBorder[d],n.style.height=r(g[1]),n.style.width=r(g[0]),S&&(n.style.transform="scale("+e.toString()+","+e.toString()+")",n.style["-ms-transform:"]="scale("+e.toString()+","+e.toString()+")",n.style["-webkit-transform"]="scale("+e.toString()+","+e.toString()+")");for(d=0;d<K.length;d++)K[d](e);this.c0=this.d1/(l+m);k[0]||(this.C2[0]=0);k[1]||(this.C2[1]=0);k[2]||(this.C2[2]=0);e=[0,0,0];m=g=1;1!=this.D&&(m=parseFloat(l)/
this.D);n=!1;for(d=0;3>d;d++)e[d]=m*q(getComputedStyle(this.X2[d]).left),isNaN(e[d])&&(e[d]=0),this.H0[d]?e[d]+l>f&&!k[d]&&this._2(d,!1):(1==this.Z2&&this.M1[d]&&(n=!0),e[d]+l>f&&(e[d]=f-l),this.C2[d]=e[d]+l),e[d]+l>g&&k[d]&&this.Q0[d]&&(g=e[d]+l);0===this.Z2?J.L2()?(this.M0.style.width=r(f),this.R0=f):this.M0.style.width=r(g):n||(k=m*q(getComputedStyle(this.M0).width),k>f&&(k=f),g=k,this.O1(this.K1*m,this.R0*m,k,-1));for(d=0;3>d;d++)this.H0[d]?this.X2[d].style.left=r(0+e[d]):this.j2(d,this.E1[d]*
m,this.P2[d]*m,e[d],-1,this.C[d],this.Q0[d]);this.D=l;this.R(g);this.M0.style.top=r((a[1]+b[1])*c);this.M0.style.height=r(s);for(d=0;4>d;d++)h[d]=r(h[d]);this.M0.style.padding=h.join(" ");for(d=0;3>d;d++)this.X2[d].style.width=r(l),this.X2[d].style.height=r(s),this.X2[d].style.top=r(0)},e1:function(a,b,e,d,c,f,h){this.b[a]=h;b=e?b*(this.D+this.P):q(getComputedStyle(this.X2[b]).left);e=q(getComputedStyle(this.X2[a]).left);this.E1[a]=e;this.M1[a]=!1;this.j2(a,this.E1[a],b,e,d,c,f)},U:function(a,b){var e=
0;try{if("col"==a.slice(0,-1)){var d=parseInt(a.slice(-1));this.X2[d].style.left=r(b);this.C2[d]=b+this.D;for(var c=[0],f=[],e=0;3>e;e++)z[e]&&(1500<getComputedStyle(this.X2[e]).zIndex&&c.push(this.P2[e]),f.push(this.C2[e]));var h=Math.max.apply(Math,c)+this.D;if(this.b[d]){for(var g=c=-1,e=0;3>e;e++)e!=d&&z[e]&&this.C2[e]>c&&parseInt(getComputedStyle(this.X2[e]).zIndex)>parseInt(getComputedStyle(this.X2[d]).zIndex)&&(c=this.C2[e],g=e);if(-1<g){this.D3(d,g);var m=Math.abs(c-this.D-this.E1[d])*this.c0*
this.J[d];this.Q2.f(a).G=c-this.D;this.Q2.f(a).V=m;if(this.M1[d]){var k=Math.abs(c-this.K1)*this.c0*this.M;this.R0=c;this.Q2.f("iPar").G=c;this.Q2.f("iPar").V=k}}}var l=this.C2[d]==Math.max.apply(Math,f),q=10<Math.abs(h-this.R0),n=this.Z2!=d||!this.M1[d],s=z[d]&&this.Q0[d];if(l&&q&&n&&s){var t;this.M1[d]=!0;this.Z2=d;t=this.C2[d]+5;e=30/29;h>t&&(e=29/30);this.M=e*this.J[d];this.O1(this.K1,h,t,-1)}}else"iPar"==a&&(this.M0.style.width=r(b),this.J2=b,this.R(b))}catch(v){}},R1:function(a){try{if("col"==
a.slice(0,-1)){var b=parseInt(a.slice(-1));this.b[b]&&(this.P2[b]=this.Q2.f(a).G);this.X2[b].style.left=r(this.P2[b]);this.C2[b]=this.P2[b]+this.D;this.Q0[b]=!0;this.E1[b]=this.P2[b];this.H0[b]=!0;this.X2[b].style.zIndex=this.C[b].toString();this.M1[b]=!1;this.S2(b)}else"iPar"==a&&(this.M0.style.width=r(this.R0),this.K1=this.R0,this.Z2=-1,this.M1=[!1,!1,!1])}catch(e){}},a0:function(a){},O1:function(a,b,e,d){this.K1=a;this.R0=b;0<=e&&(this.M0.style.width=r(e),a=e);0<d&&(this.M=d*Math.min((this.D+this.P)/
Math.max(Math.abs(b-a),0.001),1));e=Math.abs(b-a)*this.c0*this.M;if(0.1>Math.abs(b-a))this.U("iPar",b),this.R1("iPar");else{var c=this;this.Q2.U1("iPar",a,b,e,function(a){c.U("iPar",a)},function(){c.R1("iPar")},function(){c.a0("iPar")})}},j2:function(a,b,e,d,c,f,h){this.M1[a]=!1;this.H0[a]=!1;this.P2[a]=e;this.C[a]=f;this.Q0[a]=h;this.h(a);0<=d&&(this.X2[a].style.left=r(d),b=d);0<c&&(this.J[a]=c*Math.min((this.D+this.P)/Math.max(Math.abs(e-b),0.001),1));d=Math.abs(e-b)*this.c0*this.J[a];if(0.1>Math.abs(e-
b)||0.01>c&&0<=c)this.U("col"+a.toString(),e),this.R1("col"+a.toString());else{var g=this;this.Q2.U1("col"+a.toString(),b,e,d,function(b){g.U("col"+a.toString(),b)},function(){g.R1("col"+a.toString())},function(){g.a0("col"+a.toString())})}}};O.prototype={N0:function(){this.f2++;return this.f2},X0:function(){this._3--;return this._3},i:function(a,b){return-1<a.indexOf(b)},T2:function(a,b){this.I0.C[a]=b;this.I0.X2[a].style.zIndex=b.toString()},H2:function(a){return z[a]},_2:function(a,b){1==b?(this.I0.X2[a].style.visibility=
"visible",this.I0.X2[a].style.display="block",this.I0.X2[a].style.zIndex=this.I0.C[a].toString()):this.I0.X2[a].style.zIndex="-1000";z[a]=b},D1:function(a,b,e,d,c){this.V1?(this._2(a,!1),this.I0.e1(a,b,!0,1,e,d,c),this._2(a,!0)):this.I0.e1(a,b,!0,1,e,d,c)},B3:function(a,b,e,d,c,f){this.I0.e1(a,b,e,0.001,d,c,f);this._2(a,!0)},B0:function(a,b,e){for(var d=[],c=!1,f=0;f<a.length;f++)if(a[f]!=b)d.push(a[f]),c&&this.D1(a[f],f-1,this.E0,!0,!1);else if(this.T2(a[f],this.N0()),f+1==a.length)this.D1(a[f],
f-1,this.c,e,!0),this.I0.c1([b],b,0);else if(e){for(var c=!0,h=[],g=f+1;g<a.length;g++)h.push(a[g]);0<h.length&&this.I0.c1(h,b,0)}else this.D1(a[f],f+1,this.c,!0,!1),this.I0.c1([b],b,0);return d},f0:function(a,b,e){this.H2(a)||(0===b.length?this.B3(a,0,!0,this.E0,!0,!1):this.B3(a,b[e],!1,this.X0(),!0,!1))},A:function(a,b,e,d){for(var c=[],f=0;f<a.length||0===f;f++)if(f==e){this.f0(b,a,f);this.T2(b,this.X0());this._2(b,!0);this.I0.c1([b],b,1);this.D1(b,f,0===a.length||d?this.E0:this.X0(),!0,!1);c.push(b);
if(0!==a.length&&!d){for(var h=[],g=f;g<a.length;g++)h.push(a[g]);0<h.length&&this.I0.c1(h,b,1);for(g=a.length-1;g>=f;g--)this.D1(a[g],g+1,this.E0,!0,!1)}0<a.length&&c.push(a[f])}else c.push(a[f]),f+1==a.length&&a.length==e&&(this.V1?(this.B3(b,f+1,!0,this.X0(),!0,!1),this.T2(b,this.E0)):(this.f0(b,a,f),this.T2(b,this.X0()),this._2(b,!0),this.I0.c1([b],b,1),this.D1(b,f+1,this.E0,!0,!1)),c.push(b));return c},Q1:function(a,b){var e=a[1-b],d=a[b],c,f;for(c=0;3>c;c++)if(c!=e&&c!=d){f=c;break}c=[];c.push(e);
c.push(f);this.I0.c1(c,d,0);this.B3(f,e,!1,this.X0(),!0,!1);this._2(f,!0);this.D1(f,1-b,this.X0(),!0,!1);c=[];c.push(e);this.T2(d,this.N0());this.I0.c1(c,f,1);this.D1(e,b,this.E0,!0,!1);a[b]=e;a[1-b]=f;return a},g1:function(a,b){var e=[-1];this.B3(b,0,!0,this.E0,!0,!1);this.B3(a[0],0,!0,this.N0(),!0,!1);this._2(b,!0);this._2(a[0],!1);e[0]=b;return e},i1:function(a,b,e,d){for(var c=[],f=b<e,g,h=0;h<a.length;h++)g=(b+h)%a.length,0===h?(c[Math.min(e,a.length-1)]=a[g],this.T2(a[g],this.X0()),this.D1(a[g],
e,this.E0,f?!0:d,!1)):f&&b<g&&g<=e?(d&&this.D1(a[g],g-1,this.E0,d,!1),c[g-1]=a[g]):!f&&e<=g&&g<b?(d&&this.D1(a[g],g+1,this.E0,d,!1),c[g+1]=a[g]):c[g]=a[g];return c},W1:function(a){var b=this;if(b.N2==a)if(-1==b.I0.Z2&&b.I0.H0[0]&&b.I0.H0[1]&&b.I0.H0[2]){for(var e=0;e<b.E3.length;e++)b.B3(b.E3[e],e,!0,b.I0.C[b.E3[e]],!0,!1);b.N2=0}else c.setTimeout(function(){b.W1(a)},5)},O:function(){this.N2+=1;this.W1(this.N2)},Z:function(a,b){var e=[];this.E3=b;var d;for(d=0;d<a.length;d++)e.push(a[d]);if(a.length==
b.length)for(d=0;d<a.length&&a[d]==b[d];d++)if(d+1==a.length)return;if(1==a.length&&1==b.length)return this.g1(e,b[0]),b;if(2==a.length&&2==b.length)return a[0]==b[1]&&a[1]==b[0]?this.i1(e,0,1,!0):a[0]==b[1]||a[1]==b[0]?this.Q1(e,a[0]==b[1]?1:0):(d=a[0]==b[0]?1:0,e=this.B0(e,a[d],!1),this.A(e,b[d],d,!0)),b;if(2==a.length&&3==b.length){if(a[0]==b[2]&&a[1]==b[1])return e=this.i1(e,0,2,!1),this.A(e,b[0],0,!1),b;if(a[0]==b[1]&&a[1]==b[0])return e=this.i1(e,1,0,!0),this.A(e,b[2],2,!1),b;if(a[0]==b[2]&&
a[1]==b[0])return this.T2(a[0],this.X0()),this.T2(a[1],this.X0()),this.f0(b[1],e,1),this.D1(a[1],0,this.E0,!1,!1),this.D1(a[0],2,this.E0,!0,!1),this.D1(b[1],1,this.X0(),!0,!1),this.I0.c1([a[0],a[1]],b[1],1),b}else if(3==a.length&&2==b.length){if(a[2]==b[0]&&a[1]==b[1])return e=this.B0(e,a[0],!1),this.i1(e,1,0,!0),b;if(a[0]==b[1]&&a[1]==b[0])return e=this.B0(e,a[2],!0),this.i1(e,0,1,!0),b;if(a[2]==b[0]&&a[0]==b[1])return this.T2(a[2],this.X0()),this.T2(a[0],this.X0()),this.T2(a[1],this.N0()),this.D1(a[2],
0,this.E0,!0,!1),this.D1(a[0],1,this.E0,!1,!1),this.I0.c1([a[0]],a[1],0),b}for(d=0;d<e.length;)this.i(b,e[d])?d++:e=this.B0(e,e[d],!0);var c=[];for(d=0;d<b.length;d++)this.i(e,b[d])&&c.push(b[d]);for(d=0;d<e.length;d++)for(var f=0;f<c.length;f++)if(e[d]==c[f]){d!=f&&(e=this.i1(e,d,f,!0));break}for(d=0;d<b.length;d++)if(d>=e.length||b[d]!=e[d])e=this.A(e,b[d],d,!1)},setSlidespeed:function(a){this.I0.setSlidespeed(a)},getSlidespeed:function(){return this.I0.getSlidespeed()}};return h}(window,document,
navigator,console,TriFold)(c,f,g,h)};TriFold.Behavior=function(){};TriFold.Behavior.prototype={getLayout:function(c){},getButtonStatus:function(c){},onManipUse:function(c,f){},onAvailChange:function(c){},onWidgetUse:function(){}};TriFold.LEFT=0;TriFold.CENT=1;TriFold.RIGHT=2;TriFold.TWO_AVAILABLE=1;TriFold.THREE_AVAILABLE=2;TriFold.LayoutManip=function(){this.Y0=[-1,-1,-1]};
TriFold.LayoutManip.prototype={NOCHANGE:3,ENABLED:2,DISABLED:1,HIDDEN:0,BUTTON_TWO:2,BUTTON_ONE:1,CONTAINER:0,isDefault:!1,A3:function(c,f){f!=this.J1&&(this.Y0[c]=status)},h0:function(c){return this.Y0[c]},C1:function(c){}};
TriFold.DefaultManip=function(c,f){TriFold.LayoutManip.call(this);this.Q=f;this.d=[];this.O0=[];this.J1=3;this.Z0=2;this.P1=1;this.B2=0;this.W2=2;this.T=1;this.T0=0;for(var g=function(f,g){return function(){c.simulateButtonPress(f,g)}},h=0;2>h;h++)this.O0.push(g(f,h));this.E2=[!1,!1];this.B=0;this.j0=this.S1=!1};TriFold.DefaultManip.prototype=Object.create(TriFold.LayoutManip.prototype);
TriFold.DefaultManip.prototype.F=function(){this.j0=!0;for(var c=0;c<this.d.length;c++)this.Y0[this.T0]==this.Z0&&this.Y0[c+1]==this.Z0&&this.d[c].addEventListener("click",this.O0[c],!1)};TriFold.DefaultManip.prototype.e2=function(c,f){this.d.push(c);this.A3(1==this.d.length?this.T:this.W2,f)};TriFold.DefaultManip.prototype.g0=function(c,f){this.B=c;this.A3(this.T0,f)};TriFold.DefaultManip.prototype.C1=function(c){if(c==this.T)return this.d[0];if(c==this.W2)return this.d[1]};
TriFold.DefaultManip.prototype.g=function(c){if(c!=this.S1||1!=c)this.S1=c,this.B.style.opacity=c?0.5:0};
TriFold.DefaultManip.prototype.A3=function(c,f){if(f!=this.Y0[c]&&f!=this.J1){if(c==this.T0&&0!==this.B){this.g(f!=this.B2);f==this.Z0&&(this.B.style.opacity=1);for(var g=1;3>g;g++)this.Y0[g]==this.Z0&&(f==this.Z0?(this.E2[g-1]=!0,this.j0&&this.d[g-1].addEventListener("click",this.O0[g-1],!1)):f!=this.J1&&(this.E2[g-1]=!1,this.j0&&this.d[g-1].removeEventListener("click",this.O0[g-1],!1)))}else if(c==this.T&&0<this.d.length||c==this.W2&&1<this.d.length){var g=c==this.T?0:1,h=this.d[g];f==this.B2?h.style.opacity=
0:f==this.P1?h.style.opacity=0.5:f==this.Z0&&(h.style.opacity=1);this.Y0[this.T0]==this.Z0&&(f==this.Z0?(this.E2[g]=!0,this.j0&&h.addEventListener("click",this.O0[g],!1)):(this.E2[g]=!1,this.j0&&h.removeEventListener("click",this.O0[g],!1)))}this.Y0[c]=f}};TriFold.DefaultManip.prototype.P0=!0;var defaultBehaviorConsts={ONE_AVAILABLE:0,TWO_AVAILABLE:1,THREE_AVAILABLE:2,FIXED:0,SLIDE:1,CAN_MINIMIZE:2,LEFT:0,CENT:1,RIGHT:2,NO_ROLLOVER:0,ROLLOVER:1,ROLLOVER_OPT:2};
TriFold.DefaultBehavior=function(){for(var c in defaultBehaviorConsts)defaultBehaviorConsts.hasOwnProperty(ii)&&(this[c]=defaultBehaviorConsts[c]);this.C3=0;this.M2=1;this.B1=0;this.a1=1;this.a2=2;this.J0=3;this.B2=0;this.Z0=2;this.T0=0;this.T=1;this.W2=2;this.b1=!0;this.F3=!1;this.N=[this.CENT];this.K2=[this.RIGHT,this.CENT];this.H=[[],this.N.slice(0),this.K2.slice(0),[this.LEFT,this.CENT,this.RIGHT]];this.S0=0;this.F0=[this.CAN_MINIMIZE,this.CAN_MINIMIZE,this.CAN_MINIMIZE];this.j=[this.CENT];this.W=
[this.CENT];this.h1=this.NO_ROLLOVER;this.O2=!0};for(var ii in defaultBehaviorConsts)defaultBehaviorConsts.hasOwnProperty(ii)&&(TriFold.DefaultBehavior[ii]=defaultBehaviorConsts[ii]);
TriFold.DefaultBehavior.prototype={resetToDefaults:function(){this.H=[[],this.N.slice(0),this.K2.slice(0),[this.LEFT,this.CENT,this.RIGHT]]},setOpts:function(c){for(var f in c)c.hasOwnProperty(f)&&"set"+f in this&&this["set"+f].apply(this,c[f])},setModeAll:function(c){this.F0=[c,c,c]},setMode:function(c,f){this.F0[c]=f},getMode:function(c){return this.F0[c]},setDefaultOneCol:function(c){this.N=[c]},getDefaultOneCol:function(){return this.N[0]},setDefaultTwoCol:function(c){this.K2=c.slice(0)},getDefaultTwoCol:function(){return this.K2.slice(0)},
setVisTwoCol:function(c){this.j=c.slice(0)},getVisTwoCol:function(){return this.j.slice(0)},setVisThreeCol:function(c){this.W=c.slice(0)},getVisThreeCol:function(){return this.W.slice(0)},setOrderedThreeCol:function(c){this.O2=c},getOrderedThreeCol:function(){return this.O2},setRolloverTwoCol:function(c){this.h1=c},getRolloverTwoCol:function(){return this.h1},onWidgetUse:function(){this.b1&&(this.b1=!1,1!=this.S0?this.H[1][0]!=this.CENT&&(this.H[1]=this.N.slice(0)):2!=this.S0&&2>this.H[2].length?
this.H[2]=this.K2.slice(0):3!=this.S0&&3>this.H[3].length&&(this.H[3]=[this.LEFT,this.CENT,this.RIGHT]));this.F3&&(this.F3=!1,3==this.S0&&2==this.H[3].length&&(this.H[2]=this.H[3].slice(0)))},getLayout:function(c){return this.H[c].slice(0)},getButtonStatus:function(c){var f,g=this.B2,h=this.Z0,s=this.FIXED,v=this.SLIDE,w=this.b0,k=this.TWO_AVAILABLE,m=this.THREE_AVAILABLE;f=function(){return[h,h,h]};var l=this.H[c],q=[[g,g,g],[g,g,g],[g,g,g]];if(1==c&&this.F0[w]!==s)q=[f(),f(),f()];else if(2==c&&
this.F0[k]!==s)this.F0[k]==v?1==this.j.length?(c=this.j[0],q[c]=this.h1==this.ROLLOVER_OPT?f():l[0]==c?[h,g,h]:[h,h,g]):(q[l[0]]=[h,g,h],q[l[1]]=[h,h,g]):1==this.j.length?q[this.j[0]]=f():q=[f(),f(),f()];else if(3==c&&this.F0[m]!==s)if(this.F0[m]==v)q[l[0]]=[h,g,h],q[l[1]]=f(),q[l[2]]=[h,h,g];else if(0===this.W.length)q=[f(),f(),f()];else if(1==this.W.length)q[this.W[0]]=f();else for(l=3-(this.W[0]+this.W[1]),f=0;2>f;f++)q[this.W[f]]=2==l||1==l&&2==this.W[f]?[h,g,h]:[h,h,g];return q},copy:function(){var c=
new TriFold.DefaultBehavior;c.setDefaultOneCol(this.N[0]);c.setDefaultTwoCol(this.K2);c.setMode(this.b0,this.F0[this.b0]);c.setMode(this.TWO_AVAILABLE,this.F0[this.TWO_AVAILABLE]);c.setMode(this.THREE_AVAILABLE,this.F0[this.THREE_AVAILABLE]);c.setVisTwoCol(this.j);c.setVisThreeCol(this.W);c.setRolloverTwoCol(this.h1);c.setOrderedThreeCol(this.O2);return c},onManipUse:function(c,f){var g,h,s;this.F3=!0;s=this.SLIDE;var v=this.TWO_AVAILABLE,w=this.THREE_AVAILABLE,k=this.H[this.S0].slice(0);h=f;if(0===
c||1==c&&1==f)h=f+1;g=0;1<k.length&&k[1]==c&&(g=1);1==this.S0?k[0]=h:2==this.S0?this.F0[v]==s?2==this.j.length?(k.push(k[0]),k.splice(0,1)):(h=3-(k[1-g]+c),this.h1==this.ROLLOVER?(k[1-g]=c,k[g]=h):k[1-g]=h):-1<k.indexOf(h)?k.splice(k.indexOf(h),1):(1==this.j.length?(s=1-this.K2.indexOf(c),this.h1==this.ROLLOVER&&-1==this.K2.indexOf(h)&&(s=1-s)):(s=1-g,this.h1==this.ROLLOVER&&2==k.length&&(s=g)),k=[c,c],k[s]=h):3==this.S0&&(2<k.length&&k[2]==c&&(g=2),this.F0[w]==s?(k.splice(g,1),k.splice(g+(1==f?1:
-1),0,c)):-1<k.indexOf(h)?k.splice(k.indexOf(h),1):!this.O2&&(0===this.W.length||0===c||1==c&&2==k.length)||this.O2&&2==h?k.push(h):this.O2&&0!==h&&2!=k[0]?k.splice(1,0,1):k.splice(0,0,h));this.H[this.S0]=k.slice(0)},onAvailChange:function(c){this.b1=!0;this.F3=!1;c!=this.S0&&(3==this.S0&&2==c&&2>=this.H[3].length&&(this.H[2]=this.H[3].slice(0)),this.S0=c)}};
TriFold.ResizeSensor=function(c,f){function g(c,f){window.OverflowEvent?c.addEventListener("overflowchanged",function(c){f.call(this,c)}):(c.addEventListener("overflow",function(c){f.call(this,c)}),c.addEventListener("underflow",function(c){f.call(this,c)}))}function h(){this.I=[];this.add=function(c){this.I.push(c)};var c,f;this.call=function(){c=0;for(f=this.I.length;c<f;c++)this.I[c].call()}}function s(c,f){return c.currentStyle?c.currentStyle[f]:window.getComputedStyle?window.getComputedStyle(c,
null).getPropertyValue(f):c.style[f]}function v(c,f){if(!c.resizedAttached)c.resizedAttached=new h,c.resizedAttached.add(f);else if(c.resizedAttached){c.resizedAttached.add(f);return}if("onresize"in c)c.attachEvent?c.attachEvent("onresize",function(){c.resizedAttached.call()}):c.addEventListener&&c.addEventListener("resize",function(){c.resizedAttached.call()});else{var k,r=function(){(k()||1)&&c.resizedAttached.call()};c.resizeSensor=document.createElement("div");c.resizeSensor.className="resize-sensor";
c.resizeSensor.style.cssText="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1;";c.resizeSensor.innerHTML='<div class="resize-sensor-overflow" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1;"><div></div></div><div class="resize-sensor-underflow" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1;"><div></div></div>';c.appendChild(c.resizeSensor);"absolute"!==s(c,"position")&&
(c.style.position="relative");var v=-1,w=-1,A=c.resizeSensor.firstElementChild.firstChild.style,B=c.resizeSensor.lastElementChild.firstChild.style;k=function(){var f=!1,g=c.resizeSensor.offsetWidth,h=c.resizeSensor.offsetHeight;v!=g&&(A.width=g-1+"px",B.width=g+1+"px",f=!0,v=g);w!=h&&(A.height=h-1+"px",B.height=h+1+"px",f=!0,w=h);return f};k();g(c.resizeSensor,r);g(c.resizeSensor.firstElementChild,r);g(c.resizeSensor.lastElementChild,r)}}if("array"===typeof c)for(var w=0,k=c.length;w<k;w++)v(c[w],
f);else v(c,f)};

