var TriFold=function(e,f,h,g){return new new function(e,f,h,g,v){function l(){V&&r.K1(!0)}function q(a){return parseFloat(a.slice(0,-2))}function n(a){return a.toString()+"px"}function W(){X.call(this);if(e.attachEvent)e.attachEvent("onload",void 0);else if(e.onload){var a=e.onload;e.onload=function(){a();(void 0)()}}else e.onload=void 0}function X(){for(var a=function(){return function(){r.K1(!1)}}(),b=0;3>b;b++)w[b]._0&&w[b].V1();e.addEventListener("resize",a)}function K(){}function L(a,b){this.E=
b;this.g0=0;this.d=a;this.F2=[];this.A2=[[-1,-1,-1],[-1,-1,-1],[-1,-1,-1]]}function M(){if(this.T=/Android|webOS|iPhone|iPod|BlackBerry|IEMobile|Opera Mini/i.test(h.userAgent))t.className+=" onPhone"}function N(a,b,d){this.h0=a;this.g2=b;this.E=d;this.e0=10;this.S1=[240,400];this.d0=[20,30,40,30];this.g1=[18,12,15,12];this.g0=0;this.Z=!1;this.h=[0,0]}function C(){this.h2={};this.N2={};this.H2=3}function O(){this.B=new C;this.D0=new C;this.A0=1;this.J1=this.h1=0;this.N1=this.e1=1;this.L=[0,0,0];this.C2=
[0,0,0];this.F1=[!1,!1,!1];this.A1=[!0,!0,!0];this.a=[!0,!0,!0];this.R1=[!1,!1,!1];this.X=[1,1,1];this.R=[0,0,0];this.P2=[];this.F0=3;this.Q1=[1,1,1];this.M0=[x.col0[0],x.col1[0],x.col2[0]];this.X1=x.innerParent[0];this.B0=0;this.f1=1E3;this.Y=0.5;this._3=this.E0=0;this.G0=this.j1=1;this.a2=1E3;this.c0=400}function P(a){this.C=a;this.W0=200;this.J2=!1;this.I2=2E3;this.d1=1E3;this.G2=2E3;this.T2=1E3;this.Z0=0;this.N=[];this.e2=-2500;this.G=2500}g=function(a,b,d,c){t=f.createElement("div");a.resetToDefaults();
D=a;Q=b;R=d;S=c;E=v.LayoutManip.prototype;w=[new v.DefaultManip(this,0),new v.DefaultManip(this,1),new v.DefaultManip(this,2)];e.manips=w;x=(new K).M2("tri-fold_",w);F=new O;G=H=new P(F);z=new L(D,G);I=new M;r=new N(t,z,G)};g.prototype={addTo:function(a){t.style.visibility="hidden";a.appendChild(t);this.redraw();t.style.visibility="visible";W.call(this)},redraw:function(){r.K1(!0)},recheckBehavior:function(){z.H1()},addScaleCallback:function(a){J.push(a)},disableDefaultScaleCallback:function(a){T=
!a;if(a)for(var b=0;3>b;b++)a=x.colContentPlusBorder[b],a.style.removeProperty("transform"),a.style.removeProperty("-ms-transform"),a.style.removeProperty("-webkit-transform")},getElement:function(){return t},getCol:function(a){return x["col"+a.toString()][0]},setMinColDimensions:function(a){r.S1=a.slice(0);l()},getMinColDimensions:function(){return r.S1.slice(0)},setPadding:function(a){r.g1=a.slice(0);l()},getPadding:function(){return r.g1.slice(0)},setMargins:function(a){r.d0=a.slice(0);l()},getMargins:function(){return r.d0.slice(0)},
setColSpacing:function(a){r.e0=a;l()},getColSpacing:function(){return r.e0},hide:function(a){t.style.visibility=a?"hidden":"visible"},setSlidespeed:function(a){H.setSlidespeed(a)},getSlidespeed:function(){return H.getSlidespeed()},setBehavior:function(a){D=a;z.setBehavior(a)},setLayoutManip:function(a,b){for(var d=[v.LayoutManip.T1,v.LayoutManip.i1,v.LayoutManip.L1],c=0;c<d.length;c++)b.J0(d[c],w[a].b0(d[c]));w[a]=b},getLayoutManip:function(a){return w[a]},simulateButtonPress:function(a,b){z.f2(a,
b)},setOpts:function(a){for(var b in a)a.hasOwnProperty(b)&&"set"+b in this&&this["set"+b].apply(this,a[b])}};var t,Q,R,S,x={},F,H,G,z,r,D,T=!0,J=[],y=[!1,!1,!1],w,I,V=!1,E=[];K.prototype={Y1:function(a,b){for(var d=0;d<b.length;d++)a.style[b[d][0]]=b[d][1]},O0:function(a,b,d){d=f.createElement("div");for(var c=0;c<b.length;c++)b[c]in this.A||(this.A[b[c]]=[]),this.A[b[c]].push(d),b[c]=this.U+b[c];d.className=b.join(" ");a.appendChild(d);return d},M2:function(a,b){this.A={};this.U=a;this.Y1(t,[]);
t.classList.add(a+"outerParent");var d=this.O0(t,["innerParent"],[]),d=this.O0(d,["innerParentRel"],[]),c,e,s,p,U,f;for(c=0;3>c;c++){p="col"+c.toString();p=this.O0(d,[p,"cols"],[]);p=this.O0(p,["colRel"],[]);p=this.O0(p,["colContentPlusBorder"],[]);p=this.O0(p,["colContent"],[]);e=this.O0(p,["switchbar","switchbar"+c.toString()],[]);b[c]._0&&b[c].E2(e,E.R0);U=this.O0(e,["switchbarRel"],[]);for(e=s=0;3>e;e++)c!=e&&(f=this.O0(U,["switchbarBtn","switchbarBtnSide"+s.toString(),"buttonCol"+e.toString()],
[]),b[c]._0&&b[c].c1(f,E.a0),s++);p.appendChild(0===c?Q:1===c?R:S)}return this.A}};L.prototype={B1:function(a){a!=this.g0&&(this.d.onAvailChange(a),this.g0=a,this.H1())},f2:function(a,b){this.d.onManipUse(a,b);this.H1()},setBehavior:function(a){this.d=a;this.d.onAvailChange(this.g0);this.H1()},getLayout:function(){return this.F2},H1:function(){var a,b,d,c;d=this.d.getLayout(this.g0);c=this.d.getButtonStatus(this.g0);for(a=0;3>a;a++)for(b=0;3>b;b++)c[a][b]!=this.A2[a][b]&&w[a].J0(b,c[a][b]);this.E.E1(this.F2,
d);this.F2=d;this.A2=c}};M.prototype={D1:function(){return this.T}};N.prototype={K1:function(a){var b=q(getComputedStyle(this.h0).width),d=q(getComputedStyle(this.h0).height);if(!isNaN(b)&&!isNaN(d)){var c=[b,d];if(a||this.h[0]!=c[0]||this.h[1]!=c[1]){this.h=c;var e=this.d0,s=this.g1;if(I.D1())for(e=[1,0,1,0],a=0;4>a;a++)s[a]=0.8*this.g1[a];var p=b/d,f=[-1,-1,-1,-1],g=[-1,-1,-1,-1],d=[s[3]+s[1],s[0]+s[2]],h=[e[3]+e[1],e[0]+e[2]];for(a=1;4>a;a++)f[a]=(this.S1[0]*a+d[0]+(a-1)*this.e0+h[0])/(this.S1[1]+
d[1]+h[1]),g[a]=this.S1[0]*a+d[0]+(a-1)*this.e0+h[0];var b=0===h[1]?0.5:e[0]/h[1],e=0===h[0]?0.5:e[3]/h[0],p=p<f[2]||c[0]<g[2]?1:p<f[3]||c[0]<g[3]?p<1.2*f[2]&&(1==this.g0||2==this.g0)?this.g0:2:p<1.2*f[3]&&2<=this.g0?this.g0:3,k=[this.S1[0]*p+d[0]+(p-1)*this.e0,this.S1[1]+d[1]],n=[k[0]+h[0],k[1]+h[1]],f=0,g=[0,0],u=[0,0],f=c[0]<=n[0]||c[1]<=n[1]?1:Math.min(c[0]/n[0],c[1]/n[1]);for(a=0;2>a;a++)c[a]<=n[a]?(g[a]=0,u[a]=1==a||1==p?Math.max(0,c[a]-f*k[a]):f*h[a]):(u[a]=f*h[a],g[a]=c[a]-f*n[a]);h=[!1,!1,
!1];c=c[0]-(u[0]+f*d[0]);if(this.Z)for(this.g0!=p&&this.g2.B1(p),this.g0=p,d=this.g2.getLayout(),a=0;a<d.length;a++)h[d[a]]=!0;F.e(u,g,f,e,b,c,[f*s[0],f*s[1],f*s[2],f*s[3]],this.S1,f*this.e0,h);this.Z||(this.g2.B1(p),this.g0=p,this.Z=!0)}}}};C.prototype={B3:function(a,b,d,c,e,s,f,h){this.j2=a;this.K=b;this.R2=d;this.P=c;this.W=e;this.G1=s;this.A3=f;this.P1=h;this.i0=[];this.I1=0},d2:function(){for(var a in this.N2)this.N2.hasOwnProperty(a)&&(this.N2[a]=-1)},T0:function(a){return this.h2[a][this.N2[a]]},
c2:function(a){if(a.id==this.N2[a.j2]){var b=(new Date).getTime(),d=Math.max(0,b-a.W),b=a.R2-a.K,d=d/a.P;1<d&&(d=1);a.G1(a.K+b*d);if(1>d){var c=this;e.setTimeout(function(){c.c2(a)},this.H2)}else a.A3(),delete this.h2[a.j2][a.id],delete this.N2[a.j2]}else a.P1(),delete this.h2[a.j2][a.id]},V0:function(a,b,d,c,e,s,f){b=new this.B3(a,b,d,c,(new Date).getTime(),e,s,f);a in this.N2||(this.N2[a]=0);this.N2[a]=(this.N2[a]+1)%1E3;b.id=this.N2[a];a in this.h2||(this.h2[a]={});this.h2[a][b.id]=b;this.c2(b)}};
O.prototype={C3:function(a,b,d){var c={};c.srcs=a;c.tgt=b;c.add=d;if(a[0]==b&&1==a.length)for(d=0;d<this.P2.length;d++)if(this.P2[d].tgt==b&&1==this.P2[d].srcs.length&&this.P2[d].srcs[0]==a[0]){this.P2.splice(d,1);break}this.P2.push(c)},F3:function(a,b){this.M0[a].style.zIndex=b?this.Q1[a].toString():"-1000";y[a]=b},H3:function(a){for(var b=0;b<this.P2.length;){var d=this.P2[b].srcs.indexOf(a);-1<d?(this.P2[b].srcs.splice(d,1),0===this.P2[b].srcs.length?(this.F3(this.P2[b].tgt,1==this.P2[b].add?!0:
!1),this.P2.splice(b,1)):b++):b++}},g:function(a,b){for(var d=0;d<this.P2.length;d++)1==this.P2[d].srcs.length&&this.P2[d].srcs[0]==a&&this.P2[d].tgt!=a&&(this.P2[d].srcs[0]=b)},i2:function(a){for(var b=0;b<this.P2.length;)this.P2[b].tgt==a&&this.P2[b].srcs[0]!=a?this.P2.splice(b,1):b++},S2:function(a){this.X1.style.left=n((this.B0+(this.f1-a))*this.Y)},setSlidespeed:function(a){this.a2=a},getSlidespeed:function(){return this.a2},e:function(a,b,d,c,e,f,h,g,k,m){var l=g[0]*d,r=g[1]*d;this.B0=a[0];
this.Y=c;this.f1=f;this.E0=h[3];this._3=0;this.G0=k;var u;for(c=0;3>c;c++)u=x.colContentPlusBorder[c],u.style.height=n(g[1]),u.style.width=n(g[0]),T&&(u.style.transform="scale("+d.toString()+","+d.toString()+")",u.style["-ms-transform:"]="scale("+d.toString()+","+d.toString()+")",u.style["-webkit-transform"]="scale("+d.toString()+","+d.toString()+")");for(c=0;c<J.length;c++)J[c](d);this.F0=this.a2/(l+k);m[0]||(this.R[0]=0);m[1]||(this.R[1]=0);m[2]||(this.R[2]=0);d=[0,0,0];k=g=1;1!=this.j1&&(k=parseFloat(l)/
this.j1);u=!1;for(c=0;3>c;c++)d[c]=k*q(getComputedStyle(this.M0[c]).left),isNaN(d[c])&&(d[c]=0),this.a[c]?d[c]+l>f&&!m[c]&&this.F3(c,!1):(1==this.h1&&this.F1[c]&&(u=!0),d[c]+l>f&&(d[c]=f-l),this.R[c]=d[c]+l),d[c]+l>g&&m[c]&&this.A1[c]&&(g=d[c]+l);0===this.h1?I.D1()?(this.X1.style.width=n(f),this.e1=f):this.X1.style.width=n(g):u||(m=k*q(getComputedStyle(this.X1).width),m>f&&(m=f),g=m,this.W1(this.J1*k,this.e1*k,m,-1));for(c=0;3>c;c++)this.a[c]?this.M0[c].style.left=n(0+d[c]):this.G3(c,this.C2[c]*k,
this.L[c]*k,d[c],-1,this.Q1[c],this.A1[c]);this.j1=l;this.S2(g);this.X1.style.top=n((a[1]+b[1])*e);this.X1.style.height=n(r);for(c=0;4>c;c++)h[c]=n(h[c]);this.X1.style.padding=h.join(" ");for(c=0;3>c;c++)this.M0[c].style.width=n(l),this.M0[c].style.height=n(r),this.M0[c].style.top=n(0)},b1:function(a,b,d,c,e,f,h){this.R1[a]=h;b=d?b*(this.j1+this.G0):q(getComputedStyle(this.M0[b]).left);d=q(getComputedStyle(this.M0[a]).left);this.C2[a]=d;this.F1[a]=!1;this.G3(a,this.C2[a],b,d,c,e,f)},S0:function(a,
b){var d=0;try{if("col"==a.slice(0,-1)){var c=parseInt(a.slice(-1));this.M0[c].style.left=n(b);this.R[c]=b+this.j1;for(var e=[0],f=[],d=0;3>d;d++)y[d]&&(1500<getComputedStyle(this.M0[d]).zIndex&&e.push(this.L[d]),f.push(this.R[d]));var h=Math.max.apply(Math,e)+this.j1;if(this.R1[c]){for(var g=e=-1,d=0;3>d;d++)d!=c&&y[d]&&this.R[d]>e&&parseInt(getComputedStyle(this.M0[d]).zIndex)>parseInt(getComputedStyle(this.M0[c]).zIndex)&&(e=this.R[d],g=d);if(-1<g){this.g(c,g);var k=Math.abs(e-this.j1-this.C2[c])*
this.F0*this.X[c];this.B.T0(a).R2=e-this.j1;this.B.T0(a).P=k;if(this.F1[c]){var m=Math.abs(e-this.J1)*this.F0*this.N1;this.e1=e;this.B.T0("iPar").R2=e;this.B.T0("iPar").P=m}}}var l=this.R[c]==Math.max.apply(Math,f),q=10<Math.abs(h-this.e1),u=this.h1!=c||!this.F1[c],r=y[c]&&this.A1[c];if(l&&q&&u&&r){var t;this.F1[c]=!0;this.h1=c;t=this.R[c]+5;d=30/29;h>t&&(d=29/30);this.N1=d*this.X[c];this.W1(this.J1,h,t,-1)}}else"iPar"==a&&(this.X1.style.width=n(b),this.A0=b,this.S2(b))}catch(v){}},F:function(a){try{if("col"==
a.slice(0,-1)){var b=parseInt(a.slice(-1));this.R1[b]&&(this.L[b]=this.B.T0(a).R2);this.M0[b].style.left=n(this.L[b]);this.R[b]=this.L[b]+this.j1;this.A1[b]=!0;this.C2[b]=this.L[b];this.a[b]=!0;this.M0[b].style.zIndex=this.Q1[b].toString();this.F1[b]=!1;this.H3(b)}else"iPar"==a&&(this.X1.style.width=n(this.e1),this.J1=this.e1,this.h1=-1,this.F1=[!1,!1,!1])}catch(d){}},c:function(a){},W1:function(a,b,d,c){this.J1=a;this.e1=b;0<=d&&(this.X1.style.width=n(d),a=d);0<c&&(this.N1=c*Math.min((this.j1+this.G0)/
Math.max(Math.abs(b-a),0.001),1));d=Math.abs(b-a)*this.F0*this.N1;if(0.1>Math.abs(b-a))this.S0("iPar",b),this.F("iPar");else{var e=this;this.B.V0("iPar",a,b,d,function(a){e.S0("iPar",a)},function(){e.F("iPar")},function(){e.c("iPar")})}},G3:function(a,b,d,c,e,f,h){this.F1[a]=!1;this.a[a]=!1;this.L[a]=d;this.Q1[a]=f;this.A1[a]=h;this.i2(a);0<=c&&(this.M0[a].style.left=n(c),b=c);0<e&&(this.X[a]=e*Math.min((this.j1+this.G0)/Math.max(Math.abs(d-b),0.001),1));c=Math.abs(d-b)*this.F0*this.X[a];if(0.1>Math.abs(d-
b)||0.01>e&&0<=e)this.S0("col"+a.toString(),d),this.F("col"+a.toString());else{var g=this;this.B.V0("col"+a.toString(),b,d,c,function(b){g.S0("col"+a.toString(),b)},function(){g.F("col"+a.toString())},function(){g.c("col"+a.toString())})}}};P.prototype={f0:function(){this.T2++;return this.T2},_2:function(){this.G2--;return this.G2},C0:function(a,b){return-1<a.indexOf(b)},I0:function(a,b){this.C.Q1[a]=b;this.C.M0[a].style.zIndex=b.toString()},V2:function(a){return y[a]},F3:function(a,b){1==b?(this.C.M0[a].style.visibility=
"visible",this.C.M0[a].style.display="block",this.C.M0[a].style.zIndex=this.C.Q1[a].toString()):this.C.M0[a].style.zIndex="-1000";y[a]=b},L0:function(a,b,d,c,e){this.J2?(this.F3(a,!1),this.C.b1(a,b,!0,1,d,c,e),this.F3(a,!0)):this.C.b1(a,b,!0,1,d,c,e)},I:function(a,b,d,c,e,f){this.C.b1(a,b,d,0.001,c,e,f);this.F3(a,!0)},O:function(a,b,d){for(var c=[],e=!1,f=0;f<a.length;f++)if(a[f]!=b)c.push(a[f]),e&&this.L0(a[f],f-1,this.G,!0,!1);else if(this.I0(a[f],this.f0()),f+1==a.length)this.L0(a[f],f-1,this.e2,
d,!0),this.C.C3([b],b,0);else if(d){for(var e=!0,h=[],g=f+1;g<a.length;g++)h.push(a[g]);0<h.length&&this.C.C3(h,b,0)}else this.L0(a[f],f+1,this.e2,!0,!1),this.C.C3([b],b,0);return c},Z2:function(a,b,d){this.V2(a)||(0===b.length?this.I(a,0,!0,this.G,!0,!1):this.I(a,b[d],!1,this._2(),!0,!1))},V:function(a,b,d,c){for(var e=[],f=0;f<a.length||0===f;f++)if(f==d){this.Z2(b,a,f);this.I0(b,this._2());this.F3(b,!0);this.C.C3([b],b,1);this.L0(b,f,0===a.length||c?this.G:this._2(),!0,!1);e.push(b);if(0!==a.length&&
!c){for(var h=[],g=f;g<a.length;g++)h.push(a[g]);0<h.length&&this.C.C3(h,b,1);for(g=a.length-1;g>=f;g--)this.L0(a[g],g+1,this.G,!0,!1)}0<a.length&&e.push(a[f])}else e.push(a[f]),f+1==a.length&&a.length==d&&(this.J2?(this.I(b,f+1,!0,this._2(),!0,!1),this.I0(b,this.G)):(this.Z2(b,a,f),this.I0(b,this._2()),this.F3(b,!0),this.C.C3([b],b,1),this.L0(b,f+1,this.G,!0,!1)),e.push(b));return e},D:function(a,b){var d=a[1-b],c=a[b],e,f;for(e=0;3>e;e++)if(e!=d&&e!=c){f=e;break}e=[];e.push(d);e.push(f);this.C.C3(e,
c,0);this.I(f,d,!1,this._2(),!0,!1);this.F3(f,!0);this.L0(f,1-b,this._2(),!0,!1);e=[];e.push(d);this.I0(c,this.f0());this.C.C3(e,f,1);this.L0(d,b,this.G,!0,!1);a[b]=d;a[1-b]=f;return a},Q2:function(a,b){var d=[-1];this.I(b,0,!0,this.G,!0,!1);this.I(a[0],0,!0,this.f0(),!0,!1);this.F3(b,!0);this.F3(a[0],!1);d[0]=b;return d},H:function(a,b,d,c){for(var e=[],f=b<d,g,h=0;h<a.length;h++)g=(b+h)%a.length,0===h?(e[Math.min(d,a.length-1)]=a[g],this.I0(a[g],this._2()),this.L0(a[g],d,this.G,f?!0:c,!1)):f&&b<
g&&g<=d?(c&&this.L0(a[g],g-1,this.G,c,!1),e[g-1]=a[g]):!f&&d<=g&&g<b?(c&&this.L0(a[g],g+1,this.G,c,!1),e[g+1]=a[g]):e[g]=a[g];return e},P0:function(a){var b=this;if(b.Z0==a)if(-1==b.C.h1&&b.C.a[0]&&b.C.a[1]&&b.C.a[2]){for(var d=0;d<b.N.length;d++)b.I(b.N[d],d,!0,b.C.Q1[b.N[d]],!0,!1);b.Z0=0}else e.setTimeout(function(){b.P0(a)},5)},Q:function(){this.Z0+=1;this.P0(this.Z0)},E1:function(a,b){var d=[];this.N=b;var c;for(c=0;c<a.length;c++)d.push(a[c]);if(a.length==b.length)for(c=0;c<a.length&&a[c]==
b[c];c++)if(c+1==a.length)return;if(1==a.length&&1==b.length)return this.Q2(d,b[0]),b;if(2==a.length&&2==b.length)return a[0]==b[1]&&a[1]==b[0]?this.H(d,0,1,!0):a[0]==b[1]||a[1]==b[0]?this.D(d,a[0]==b[1]?1:0):(c=a[0]==b[0]?1:0,d=this.O(d,a[c],!1),this.V(d,b[c],c,!0)),b;if(2==a.length&&3==b.length){if(a[0]==b[2]&&a[1]==b[1])return d=this.H(d,0,2,!1),this.V(d,b[0],0,!1),b;if(a[0]==b[1]&&a[1]==b[0])return d=this.H(d,1,0,!0),this.V(d,b[2],2,!1),b;if(a[0]==b[2]&&a[1]==b[0])return this.I0(a[0],this._2()),
this.I0(a[1],this._2()),this.Z2(b[1],d,1),this.L0(a[1],0,this.G,!1,!1),this.L0(a[0],2,this.G,!0,!1),this.L0(b[1],1,this._2(),!0,!1),this.C.C3([a[0],a[1]],b[1],1),b}else if(3==a.length&&2==b.length){if(a[2]==b[0]&&a[1]==b[1])return d=this.O(d,a[0],!1),this.H(d,1,0,!0),b;if(a[0]==b[1]&&a[1]==b[0])return d=this.O(d,a[2],!0),this.H(d,0,1,!0),b;if(a[2]==b[0]&&a[0]==b[1])return this.I0(a[2],this._2()),this.I0(a[0],this._2()),this.I0(a[1],this.f0()),this.L0(a[2],0,this.G,!0,!1),this.L0(a[0],1,this.G,!1,
!1),this.C.C3([a[0]],a[1],0),b}for(c=0;c<d.length;)this.C0(b,d[c])?c++:d=this.O(d,d[c],!0);var e=[];for(c=0;c<b.length;c++)this.C0(d,b[c])&&e.push(b[c]);for(c=0;c<d.length;c++)for(var f=0;f<e.length;f++)if(d[c]==e[f]){c!=f&&(d=this.H(d,c,f,!0));break}for(c=0;c<b.length;c++)if(c>=d.length||b[c]!=d[c])d=this.V(d,b[c],c,!1)},setSlidespeed:function(a){this.C.setSlidespeed(a)},getSlidespeed:function(){return this.C.getSlidespeed()}};return g}(window,document,navigator,console,TriFold)(e,f,h,g)};
TriFold.Behavior=function(){};TriFold.Behavior.prototype={getLayout:function(e){},getButtonStatus:function(e){},onManipUse:function(e,f){},onAvailChange:function(e){},onWidgetUse:function(){}};TriFold.LEFT=0;TriFold.CENT=1;TriFold.RIGHT=2;TriFold.TWO_AVAILABLE=1;TriFold.THREE_AVAILABLE=2;TriFold.LayoutManip=function(){this.Y0=[-1,-1,-1]};
TriFold.LayoutManip.prototype={NOCHANGE:3,ENABLED:2,DISABLED:1,HIDDEN:0,BUTTON_TWO:2,BUTTON_ONE:1,CONTAINER:0,isDefault:!1,J0:function(e,f){f!=this.M&&(this.Y0[e]=status)},b0:function(e){return this.Y0[e]},X0:function(e){}};
TriFold.DefaultManip=function(e,f){TriFold.LayoutManip.call(this);this.D3=f;this.i=[];this.B2=[];this.M=3;this.a0=2;this.Q0=1;this.R0=0;this.i1=2;this.T1=1;this.L1=0;for(var h=function(f,g){return function(){e.simulateButtonPress(f,g)}},g=0;2>g;g++)this.B2.push(h(f,g));this.D2=[!1,!1];this.U1=0;this.O1=this.j0=!1};TriFold.DefaultManip.prototype=Object.create(TriFold.LayoutManip.prototype);
TriFold.DefaultManip.prototype.V1=function(){this.O1=!0;for(var e=0;e<this.i.length;e++)this.Y0[this.L1]==this.a0&&this.Y0[e+1]==this.a0&&this.i[e].addEventListener("click",this.B2[e],!1)};TriFold.DefaultManip.prototype.c1=function(e,f){this.i.push(e);this.J0(1==this.i.length?this.T1:this.i1,f)};TriFold.DefaultManip.prototype.E2=function(e,f){this.U1=e;this.J0(this.L1,f)};TriFold.DefaultManip.prototype.X0=function(e){if(e==this.T1)return this.i[0];if(e==this.i1)return this.i[1]};
TriFold.DefaultManip.prototype.O2=function(e){if(e!=this.j0||1!=e)this.j0=e,this.U1.style.opacity=e?0.5:0};
TriFold.DefaultManip.prototype.J0=function(e,f){if(f!=this.Y0[e]&&f!=this.M){if(e==this.L1&&0!==this.U1){this.O2(f!=this.R0);f==this.a0&&(this.U1.style.opacity=1);for(var h=1;3>h;h++)this.Y0[h]==this.a0&&(f==this.a0?(this.D2[h-1]=!0,this.O1&&this.i[h-1].addEventListener("click",this.B2[h-1],!1)):f!=this.M&&(this.D2[h-1]=!1,this.O1&&this.i[h-1].removeEventListener("click",this.B2[h-1],!1)))}else if(e==this.T1&&0<this.i.length||e==this.i1&&1<this.i.length){var h=e==this.T1?0:1,g=this.i[h];f==this.R0?
g.style.opacity=0:f==this.Q0?g.style.opacity=0.5:f==this.a0&&(g.style.opacity=1);this.Y0[this.L1]==this.a0&&(f==this.a0?(this.D2[h]=!0,this.O1&&g.addEventListener("click",this.B2[h],!1)):(this.D2[h]=!1,this.O1&&g.removeEventListener("click",this.B2[h],!1)))}this.Y0[e]=f}};TriFold.DefaultManip.prototype._0=!0;var defaultBehaviorConsts={ONE_AVAILABLE:0,TWO_AVAILABLE:1,THREE_AVAILABLE:2,FIXED:0,SLIDE:1,CAN_MINIMIZE:2,LEFT:0,CENT:1,RIGHT:2,NO_ROLLOVER:0,ROLLOVER:1,ROLLOVER_OPT:2};
TriFold.DefaultBehavior=function(){for(var e in defaultBehaviorConsts)defaultBehaviorConsts.hasOwnProperty(ii)&&(this[e]=defaultBehaviorConsts[e]);this.f=0;this.U2=1;this.K0=0;this.a1=1;this.U0=2;this.N0=3;this.R0=0;this.a0=2;this.L1=0;this.T1=1;this.i1=2;this.Z1=!0;this.W2=!1;this.J=[this.CENT];this.Y2=[this.RIGHT,this.CENT];this.L2=[[],this.J.slice(0),this.Y2.slice(0),[this.LEFT,this.CENT,this.RIGHT]];this.b2=0;this.b=[this.CAN_MINIMIZE,this.CAN_MINIMIZE,this.CAN_MINIMIZE];this._1=[this.CENT];this.j=
[this.CENT];this.X2=this.NO_ROLLOVER;this.C1=!0};for(var ii in defaultBehaviorConsts)defaultBehaviorConsts.hasOwnProperty(ii)&&(TriFold.DefaultBehavior[ii]=defaultBehaviorConsts[ii]);
TriFold.DefaultBehavior.prototype={resetToDefaults:function(){this.L2=[[],this.J.slice(0),this.Y2.slice(0),[this.LEFT,this.CENT,this.RIGHT]]},setOpts:function(e){for(var f in e)e.hasOwnProperty(f)&&"set"+f in this&&this["set"+f].apply(this,e[f])},setModeAll:function(e){this.b=[e,e,e]},setMode:function(e,f){this.b[e]=f},getMode:function(e){return this.b[e]},setDefaultOneCol:function(e){this.J=[e]},getDefaultOneCol:function(){return this.J[0]},setDefaultTwoCol:function(e){this.Y2=e.slice(0)},getDefaultTwoCol:function(){return this.Y2.slice(0)},
setVisTwoCol:function(e){this._1=e.slice(0)},getVisTwoCol:function(){return this._1.slice(0)},setVisThreeCol:function(e){this.j=e.slice(0)},getVisThreeCol:function(){return this.j.slice(0)},setOrderedThreeCol:function(e){this.C1=e},getOrderedThreeCol:function(){return this.C1},setRolloverTwoCol:function(e){this.X2=e},getRolloverTwoCol:function(){return this.X2},onWidgetUse:function(){this.Z1&&(this.Z1=!1,1!=this.b2?this.L2[1][0]!=this.CENT&&(this.L2[1]=this.J.slice(0)):2!=this.b2&&2>this.L2[2].length?
this.L2[2]=this.Y2.slice(0):3!=this.b2&&3>this.L2[3].length&&(this.L2[3]=[this.LEFT,this.CENT,this.RIGHT]));this.W2&&(this.W2=!1,3==this.b2&&2==this.L2[3].length&&(this.L2[2]=this.L2[3].slice(0)))},getLayout:function(e){return this.L2[e].slice(0)},getButtonStatus:function(e){var f,h=this.R0,g=this.a0,m=this.FIXED,A=this.SLIDE,B=this.S,k=this.TWO_AVAILABLE,v=this.THREE_AVAILABLE;f=function(){return[g,g,g]};var l=this.L2[e],q=[[h,h,h],[h,h,h],[h,h,h]];if(1==e&&this.b[B]!==m)q=[f(),f(),f()];else if(2==
e&&this.b[k]!==m)this.b[k]==A?1==this._1.length?(e=this._1[0],q[e]=this.X2==this.ROLLOVER_OPT?f():l[0]==e?[g,h,g]:[g,g,h]):(q[l[0]]=[g,h,g],q[l[1]]=[g,g,h]):1==this._1.length?q[this._1[0]]=f():q=[f(),f(),f()];else if(3==e&&this.b[v]!==m)if(this.b[v]==A)q[l[0]]=[g,h,g],q[l[1]]=f(),q[l[2]]=[g,g,h];else if(0===this.j.length)q=[f(),f(),f()];else if(1==this.j.length)q[this.j[0]]=f();else for(l=3-(this.j[0]+this.j[1]),f=0;2>f;f++)q[this.j[f]]=2==l||1==l&&2==this.j[f]?[g,h,g]:[g,g,h];return q},copy:function(){var e=
new TriFold.DefaultBehavior;e.setDefaultOneCol(this.J[0]);e.setDefaultTwoCol(this.Y2);e.setMode(this.S,this.b[this.S]);e.setMode(this.TWO_AVAILABLE,this.b[this.TWO_AVAILABLE]);e.setMode(this.THREE_AVAILABLE,this.b[this.THREE_AVAILABLE]);e.setVisTwoCol(this._1);e.setVisThreeCol(this.j);e.setRolloverTwoCol(this.X2);e.setOrderedThreeCol(this.C1);return e},onManipUse:function(e,f){var h,g,m;this.W2=!0;m=this.SLIDE;var A=this.TWO_AVAILABLE,B=this.THREE_AVAILABLE,k=this.L2[this.b2].slice(0);g=f;if(0===
e||1==e&&1==f)g=f+1;h=0;1<k.length&&k[1]==e&&(h=1);1==this.b2?k[0]=g:2==this.b2?this.b[A]==m?2==this._1.length?(k.push(k[0]),k.splice(0,1)):(g=3-(k[1-h]+e),this.X2==this.ROLLOVER?(k[1-h]=e,k[h]=g):k[1-h]=g):-1<k.indexOf(g)?k.splice(k.indexOf(g),1):(1==this._1.length?(m=1-this.Y2.indexOf(e),this.X2==this.ROLLOVER&&-1==this.Y2.indexOf(g)&&(m=1-m)):(m=1-h,this.X2==this.ROLLOVER&&2==k.length&&(m=h)),k=[e,e],k[m]=g):3==this.b2&&(2<k.length&&k[2]==e&&(h=2),this.b[B]==m?(k.splice(h,1),k.splice(h+(1==f?1:
-1),0,e)):-1<k.indexOf(g)?k.splice(k.indexOf(g),1):!this.C1&&(0===this.j.length||0===e||1==e&&2==k.length)||this.C1&&2==g?k.push(g):this.C1&&0!==g&&2!=k[0]?k.splice(1,0,1):k.splice(0,0,g));this.L2[this.b2]=k.slice(0)},onAvailChange:function(e){this.Z1=!0;this.W2=!1;e!=this.b2&&(3==this.b2&&2==e&&2>=this.L2[3].length&&(this.L2[2]=this.L2[3].slice(0)),this.b2=e)}};
